FUNCTION FINDNEXTBYBROWSENAME : POINTER TO SymbolsBaseNode
VAR_INPUT
	LIST : POINTER TO POINTER TO SymbolsBaseNode;
	NUMELEMENTS : DINT;
	PBROWSENAME : POINTER TO OpcUa_QualifiedName;
	VARINFO : REFERENCE TO VariableInformation;
END_VAR
VAR_OUTPUT
	RESULT : RTS_IEC_RESULT;
END_VAR
VAR_IN_OUT
	INDEX : DINT;
END_VAR
END_FUNCTION