FUNCTION SETTGGETSTRINGVALUE : RTS_IEC_RESULT
VAR_INPUT
	PSZCOMPONENT : REFERENCE TO STRING;
	PSZKEY : REFERENCE TO STRING;
	PSZVALUE : POINTER TO STRING;
	PILEN : POINTER TO DINT;
	PSZDEFAULT : REFERENCE TO STRING;
	BCACHED : DINT;
END_VAR
END_FUNCTION