FUNCTION L_MB1P_CHECKREQUESTSINFO : BOOL
VAR_OUTPUT
	XRTRIG : BOOL;
	XFTRIG : BOOL;
	DWRTRIG : DWORD;
	DWFTRIG : DWORD;
END_VAR
VAR_IN_OUT
	DWREQUESTSINFO : DWORD;
	DWREQUESTSINFO_OLD : DWORD;
END_VAR
END_FUNCTION