FUNCTION L_MB1P_POSITIONINSIDEWINDOW : BOOL
VAR_INPUT
	LRPOSIN : LREAL;
	LRLOWERWINDOW : LREAL;
	LRUPPERWINDOW : LREAL;
END_VAR
VAR_OUTPUT
	XERROR : BOOL := FALSE;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION