FUNCTION L_MB1P_IDENTMAXPOSSIBLEDIAMETER : LREAL
VAR_INPUT
	WIDENTDIAMCALCCYCLES : WORD := 1;
END_VAR
VAR_IN_OUT
	LRACTDANCERPOSIN : LREAL;
	LRMAXDANCERPOS : LREAL;
	LRDANCERMATERIALLENGTH : LREAL;
	LRDIAMCALCDIST : LREAL;
END_VAR
END_FUNCTION