using System.Collections.Generic;
using System.Linq;
using Xunit;
using Volt.Contracts;
using Volt.Engine.Format.Body;
using Volt.Engine.Item;
using Volt.Engine.Sync;

namespace Volt.Engine.Tests;

/// <summary>
/// A DUT on the wire: ONE internal kind (<c>Kinds.Dut</c>), FOUR tree codes on TwinCAT, and a wire NAME that
/// carries its SUBTYPE — <c>X.struct</c> / <c>X.enum</c> / <c>X.union</c> / <c>X.alias</c>, read from the
/// declaration (openspec <c>dut-subtype-on-the-wire</c>).
/// <para><b>The tree-code half pinned silent data loss.</b> <c>ItemKind</c> asserted that 605/606/607 — the
/// enum/struct/union codes — were "never produced, never needed". They are: a DUT authored in the TwinCAT IDE
/// carries one (the committed <c>TwinCAT Project14</c> fixture's <c>E_PackML_Mode</c> has always walked as 605).
/// An unmapped code is emitted by the walk and then dropped by Core, so those items never reached <c>refs</c> or
/// <c>fetch</c> — and to a pull, absent means DELETED.</para>
/// <para><b>The name half is why the CLI holds no DUT logic.</b> The subtype used to be hidden from the wire
/// (<c>X.dut</c>) and re-derived in the CLI to name the file, which put item-kind knowledge in the one layer
/// whose job is git. The engine names the item once, where every other wire name is minted, and a client maps
/// file name == wire name. The name comes from the DECLARATION and never from the tree code: TwinCAT's code lags
/// the declaration after an in-place change and a push-create seeds 606 whatever the body (DIALECT C2e).</para>
/// </summary>
public class DutSubtypeCodeTests
{
    /// <summary>All four codes are the one INTERNAL kind — the kind the ST reader/writer and the create path
    /// speak. Mapping without this would drop an IDE-authored DUT from every walk.</summary>
    [Theory]
    [InlineData(ItemKind.PlcDut)]        // 623 — PLCDUTALIAS on TwinCAT; what CODESYS classifies every DUT as
    [InlineData(ItemKind.PlcDutEnum)]    // 605 — E_PackML_Mode, live fixture
    [InlineData(ItemKind.PlcDutStruct)]  // 606 — what a push-create seeds on TwinCAT
    [InlineData(ItemKind.PlcDutUnion)]   // 607
    public void Every_dut_tree_code_maps_to_the_one_internal_dut_kind(int code) =>
        Assert.Equal(ItemKind.Kinds.Dut, ItemKind.Map(code));

    /// <summary>And each is a top-level source item, so the walk emits it as a file rather than descending it.
    /// Mapping without this would put the item on the wire and then mis-shape it.</summary>
    [Theory]
    [InlineData(ItemKind.PlcDut)]
    [InlineData(ItemKind.PlcDutEnum)]
    [InlineData(ItemKind.PlcDutStruct)]
    [InlineData(ItemKind.PlcDutUnion)]
    public void Every_dut_tree_code_is_top_level_crud(int code) =>
        Assert.True(ItemKind.IsTopLevelCrud(code));

    // ── the wire name ─────────────────────────────────────────────────────────────────────────────

    private const string Struct = "TYPE X :\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE";
    private const string Enum = "TYPE X :\n(\n\tIdle := 0,\n\tRun\n);\nEND_TYPE";
    private const string Union = "TYPE X :\nUNION\n\tb : BYTE;\n\tw : WORD;\nEND_UNION\nEND_TYPE";
    private const string Alias = "TYPE X : STRING(80);\nEND_TYPE";

    /// <summary>A CODESYS text-list enumeration (<c>ITextListEnumerationObject</c>, Pro2193's <c>IQSlices</c>)
    /// is the DUT kind to <c>CodesysTypeMap</c> and reaches the engine as a DUT whose declaration is an enum —
    /// here with the generated-file comment header the real one carries, which the subtype read must step over
    /// (DIALECT C2e).</summary>
    private const string TextListEnum =
        "// -----------------------------------------------------------------------------\n" +
        "// This file is auto-generated by xlsx_read_adv.py\n" +
        "{attribute 'qualified_only'}\n" +
        "TYPE X :\n(\n\tDI_10 := 0,\n\tDI_11 := 1\n) UINT;\nEND_TYPE";

    public static TheoryData<string, string> Shapes => new()
    {
        { Struct, "X.struct" },
        { Enum, "X.enum" },
        { Union, "X.union" },
        { Alias, "X.alias" },
        { TextListEnum, "X.enum" },
    };

    private static FakeIde OneDut(int code, string decl, string folder = "DUTs") =>
        new FakeIde(new FakeIde.Item("X", code, folder, true, decl, null, null, null));

    /// <summary>THE ONE MINTING SITE names a DUT by its declaration's subtype. `.dut` was the wire name for
    /// every one of these, which is what forced the CLI to read the declaration to name a file.</summary>
    [Theory]
    [MemberData(nameof(Shapes))]
    public void The_materializer_names_each_dut_shape_by_its_subtype(string decl, string wireName)
    {
        var ide = OneDut(ItemKind.PlcDut, decl);
        Assert.Equal(wireName, Materializer.Materialize(ide, "X", ItemKind.Kinds.Dut, new ItemRef("X")).FullName);
    }

    /// <summary>…and so does every wire message that carries the name: `refs` items and folders, and `fetch`.</summary>
    [Theory]
    [MemberData(nameof(Shapes))]
    public void Refs_and_fetch_publish_the_subtype_name(string decl, string wireName)
    {
        var ide = OneDut(ItemKind.PlcDut, decl);

        var refs = RefsService.Handle(ide);
        Assert.Equal(new[] { wireName }, refs.Items.Keys.ToArray());
        Assert.Equal("DUTs", refs.Folders[wireName]);

        var fetched = Assert.Single(FetchService.Handle(ide, new FetchRequest { KnownItems = new() }).Changed);
        Assert.Equal(wireName, fetched.Name);
    }

    /// <summary>THE TREE CODE NEVER DECIDES THE NAME. Measured on TwinCAT (DIALECT C2e): a 606 holding an enum,
    /// a 623 holding a struct and a 605 holding a union are all real live states — the code lags an in-place
    /// change until a reload — so a name read off the code would publish the OLD shape.</summary>
    [Theory]
    [InlineData(ItemKind.PlcDutStruct, Enum, "X.enum")]
    [InlineData(ItemKind.PlcDut, Struct, "X.struct")]
    [InlineData(ItemKind.PlcDutEnum, Struct, "X.struct")]
    [InlineData(ItemKind.PlcDutEnum, Union, "X.union")]
    [InlineData(ItemKind.PlcDutUnion, Alias, "X.alias")]
    public void The_subtype_comes_from_the_declaration_not_the_tree_code(int code, string decl, string wireName) =>
        Assert.Equal(new[] { wireName }, RefsService.Handle(OneDut(code, decl)).Items.Keys.ToArray());

    /// <summary>A DECLARATION THAT STATES NO SUBTYPE IS REFUSED, NEVER GUESSED. The subtype is a wire IDENTITY:
    /// whatever `DutSubtype` answers becomes the item's name on the wire, its file name on disk, and the key the
    /// subtype-change pairing reads. It used to answer `alias` for anything it could not classify — "the shape that
    /// assumes least" — which publishes `X.alias` for a declaration that never says so, and a later fix of the
    /// text then reads as the alias removed and a new item added. No colon, nothing after the colon, or the
    /// colon followed straight by `END_TYPE` is a declaration with no body shape at all.</summary>
    [Theory]
    [InlineData("")]
    [InlineData("TYPE X\nEND_TYPE")]
    [InlineData("TYPE X :")]
    [InlineData("TYPE X :\nEND_TYPE")]
    // Punctuation after the colon is no type either: an alias names one, so `TYPE X : ;` states nothing.
    [InlineData("TYPE X : ;\nEND_TYPE")]
    [InlineData("TYPE X :\n;\nEND_TYPE")]
    public void DutSubtype_refuses_a_declaration_that_states_no_subtype(string decl)
    {
        var ex = Assert.Throws<System.FormatException>(() => Volt.Engine.Format.St.CodeHelper.DutSubtype(decl));
        Assert.Contains("subtype", ex.Message);
    }

    /// <summary>THE SUBTYPE IS THE FIRST TOKEN AFTER THE COLON — THE FIRST CODE TOKEN. A comment or a pragma
    /// between the colon and the body is trivia, wherever it sits: at the end of the TYPE line, as a block comment
    /// before `STRUCT` on the same line or the next, or an attribute pragma before an enumeration's `(`. The
    /// reader stripped only LEADING trivia per line, so the text after the colon began with the comment itself and
    /// a STRUCT read as `alias` (a `//` comment) or `enum` (a `(*` comment opens with `(`). That answer is the
    /// item's file name today and its wire identity once the engine mints it, so a struct would be published under
    /// an enum's name — and every push of the correctly named `X.struct` refused as disagreeing with it.</summary>
    [Theory]
    [InlineData("TYPE ST_X : // note\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    [InlineData("TYPE ST_X : (* note *)\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    [InlineData("TYPE ST_X : (* note *) STRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    [InlineData("TYPE ST_X : (* a\nmulti-line note *)\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    [InlineData("TYPE U_X : // note\nUNION\n\tb : BYTE;\nEND_UNION\nEND_TYPE", "union")]
    [InlineData("TYPE E_X : {attribute 'strict'} (A, B);\nEND_TYPE", "enum")]
    [InlineData("TYPE E_X : // note\n(A, B);\nEND_TYPE", "enum")]
    [InlineData("TYPE E_X :\n{attribute 'strict'} (A, B);\nEND_TYPE", "enum")]   // the pragma on the body's own line
    [InlineData("TYPE T_X : (* note *) INT (0..10);\nEND_TYPE", "alias")]
    [InlineData("TYPE ST_X (* a colon : in a comment *) :\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    // A pragma that STARTS the TYPE line is trivia before the header, not the whole line: the previous reader
    // dropped such a line entirely, lost the type's own colon, took a member's `a : INT` (or an initializer's
    // `:=`) for it, and answered alias. Pinned because the upgrade note (items.html#dut-migration) lists the
    // rename it causes.
    [InlineData("{attribute 'pack_mode' := '1'} TYPE ST_X :\nSTRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    [InlineData("{attribute 'qualified_only'} TYPE E_X :\n(\n\tIdle := 0,\n\tRun := 1\n);\nEND_TYPE", "enum")]
    [InlineData("{attribute 'strict'} TYPE E_X :\n(A, B);\nEND_TYPE", "enum")]
    // The body keyword is a WHOLE token: an alias of a user type whose name merely BEGINS with STRUCT or UNION is
    // an alias. Matched as a prefix it was published `T.struct`, and the correctly named `T.alias` was refused.
    [InlineData("TYPE T : Struct_Alarm;\nEND_TYPE", "alias")]
    [InlineData("TYPE T : STRUCTURE_T;\nEND_TYPE", "alias")]
    [InlineData("TYPE T_Handle : StructHandle;\nEND_TYPE", "alias")]
    [InlineData("TYPE T : UNIONBITS;\nEND_TYPE", "alias")]
    [InlineData("TYPE T : Union_Word;\nEND_TYPE", "alias")]
    [InlineData("TYPE ST_X :STRUCT\n\ta : INT;\nEND_STRUCT\nEND_TYPE", "struct")]
    public void DutSubtype_reads_the_first_code_token_after_the_colon(string decl, string subtype) =>
        Assert.Equal(subtype, Volt.Engine.Format.St.CodeHelper.DutSubtype(decl));

    /// <summary>…and on the wire that refusal is an UNREADABLE item — tracked, named in `unreadable`, its file
    /// kept by every client — rather than an item published under a subtype its text never states.</summary>
    [Theory]
    [InlineData("TYPE X\nEND_TYPE")]
    [InlineData("TYPE X : ;\nEND_TYPE")]
    public void A_dut_whose_declaration_states_no_subtype_is_unreadable_not_a_guessed_alias(string decl)
    {
        var ide = OneDut(ItemKind.PlcDut, decl);

        var fetch = FetchService.Handle(ide, new FetchRequest { KnownItems = new() });

        Assert.Equal(new[] { "X" }, fetch.Unreadable.ToArray());
        Assert.Empty(fetch.Items);
        Assert.Empty(fetch.Changed);
    }

    /// <summary>…"ITS FILE KEPT" is the half that loses data, and it needs a DUT the client ALREADY HOLDS: an
    /// engineer half-way through retyping `X` in the IDE leaves `TYPE X :` with nothing after the colon. The item
    /// is still there, so the client's `X.struct` must not be reported removed — or the pull deletes the file for
    /// a DUT sitting in the IDE — and it is published under no name at all, since any name would be a guess.
    /// The known map is whatever `refs` published for the struct, so this holds before and after the rename of
    /// the wire name.</summary>
    [Theory]
    [InlineData("TYPE X :\nEND_TYPE")]
    [InlineData("TYPE X :")]
    public void A_known_dut_whose_declaration_loses_its_subtype_is_unreadable_and_not_removed(string decl)
    {
        var ide = OneDut(ItemKind.PlcDut, Struct);
        var before = RefsService.Handle(ide);

        ide.RemoveItem("X");
        ide.AddItem(new FakeIde.Item("X", ItemKind.PlcDut, "DUTs", true, decl, null, null, null));
        var fetch = FetchService.Handle(ide, new FetchRequest { KnownItems = new(before.Items) });

        Assert.Equal(new[] { "X" }, fetch.Unreadable.ToArray());
        Assert.Empty(fetch.Removed);
        Assert.Empty(fetch.Changed);
    }

    /// <summary>A SUBTYPE CHANGE IN THE IDE IS A REMOVED NAME PLUS AN ADDED ONE. That is what lets a client's
    /// ordinary removal sweep retire the old file with no DUT knowledge of its own: `fetch` against a baseline
    /// holding `X.struct` reports `X.struct` removed and `X.enum` changed.</summary>
    [Fact]
    public void A_subtype_change_in_the_ide_fetches_as_the_old_name_removed_and_the_new_one_changed()
    {
        var ide = OneDut(ItemKind.PlcDut, Struct);
        var before = RefsService.Handle(ide);

        ide.RemoveItem("X");
        ide.AddItem(new FakeIde.Item("X", ItemKind.PlcDut, "DUTs", true, Enum, null, null, null));

        var fetch = FetchService.Handle(ide, new FetchRequest { KnownItems = new(before.Items) });
        Assert.Equal(new[] { "X.struct" }, fetch.Removed.ToArray());
        Assert.Equal("X.enum", Assert.Single(fetch.Changed).Name);
    }
}
