FUNCTION APPCALLGETPROPERTY2 : RTS_IEC_RESULT
VAR_INPUT
	PINSTANCE : POINTER TO BYTE;
	PPGETMETHOD : POINTER TO POINTER TO BYTE;
	PPBYVALUE : POINTER TO POINTER TO BYTE;
	ULSIZE : __XWORD;
END_VAR
END_FUNCTION