FUNCTION APPREGISTERPROPACCESSFUNCTIONS : RTS_IEC_RESULT
VAR_INPUT
	PAPP : POINTER TO APPLICATION;
	PPFGETBOOLEANPROPERTY : POINTER TO POINTER TO BYTE;
	PPFGETTEXTPROPERTY : POINTER TO POINTER TO BYTE;
	PPFGETNUMBERPROPERTY : POINTER TO POINTER TO BYTE;
	PPFGETVERSIONPROPERTY : POINTER TO POINTER TO BYTE;
END_VAR
END_FUNCTION