FUNCTION _GETCOUNTALARMSFROMSTORAGE : DINT
VAR_INPUT
	PSTARRALARMGROUPS : POINTER TO ARRAY [0..0] OF UDINT;
	ICOUNTALARMGROUPS : INT;
	BALLALARMGROUPS : BOOL;
	PSTARRALARMCLASSES : POINTER TO ARRAY [0..0] OF UDINT;
	ICOUNTALARMCLASSES : INT;
	BALLALARMCLASSES : BOOL;
	USIPRIORITYFROM : USINT;
	USIPRIORITYTO : USINT;
	ALARMDATABLOCK : IAlarmDataBlockBase2;
END_VAR
END_FUNCTION