FUNCTION ELABORATETIMERANGEFILTERCRITERIA : BOOL
VAR_INPUT
	FILTERTYPE : EFilterTimeRangeType;
	DTFROM : DATE_AND_TIME;
	DTTO : DATE_AND_TIME;
END_VAR
VAR_OUTPUT
	FILTERTYPEELAB : EFilterTimeRangeType;
	TSFROM : Timestamp;
	TSTO : Timestamp;
END_VAR
END_FUNCTION