FUNCTION GETALARMDISPLAYOPTIONSFROMPROXY : BOOL
VAR_INPUT
	ITFALARMMETAOBJECTSTUB5 : IAlarmMetaObjectStub5;
	REFDISPLAYOPTIONS : REFERENCE TO DisplayOptions;
END_VAR
VAR_OUTPUT
	XVALID : BOOL;
	SCLASSREMAP : STRING;
END_VAR
END_FUNCTION