FUNCTION GETALARMSFROMSTORAGE2 : BOOL
VAR_INPUT
	ITFDATABASEACCESS : IDatabaseAccess;
	ISKIPROWS : INT;
	IMAXROWS : INT;
	FILTERCRITERIA : REFERENCE TO VisuFbAlarmFilterCriteria;
	ALARMDATABLOCK : IAlarmDataBlockBase2;
END_VAR
VAR_IN_OUT
	BROWIDVALID : BOOL;
	DIROWID : DINT;
END_VAR
END_FUNCTION