FUNCTION GETALARMSFROMSTORAGE6 : BOOL
VAR_INPUT
	ITFDATABASEACCESS : IDatabaseAccess;
	DISKIPROWS : DINT;
	DIMAXROWS : DINT;
	FILTERCRITERIA : REFERENCE TO VisuFbAlarmFilterCriteria;
	ALARMDATABLOCK : IAlarmDataBlockBase2;
END_VAR
VAR_IN_OUT
	BROWIDVALID : BOOL;
	DIROWID : DINT;
END_VAR
END_FUNCTION