FUNCTION RAISEORUPDATEEVENT : BOOL
VAR_INPUT
	PALARM : POINTER TO Alarm;
	LIPUTINTOEVENTQUEUEAT : Timestamp;
	PAPACTIVEALARMS : POINTER TO ARRAY [0..0] OF POINTER TO Alarm;
	ICOUNTALARMSANDEVENTS : INT;
END_VAR
VAR_IN_OUT
	ICOUNTACTIVEALARMS : INT;
END_VAR
END_FUNCTION