FUNCTION REPLACEALARMPLACEHOLDERS4NOTOPTIMIZED : BOOL
VAR_INPUT
	IWHICHMESSAGE : INT;
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	RCBSRESULT : REFERENCE TO CharBufferString;
	ITFALARMMETAOBJECTSTUB3 : IAlarmMetaObjectStub3;
	CBPMESSAGE : CharBufferPtr;
	ESTATE : AlarmState;
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	SALARMID : STRING;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION