FUNCTION REPLACEALARMMESSAGEPLACEHOLDERS3 : BOOL
VAR_INPUT
	CBSTEXT : REFERENCE TO CharBufferString;
	CBSBUFFER : REFERENCE TO CharBufferString;
	TIMESTAMP : SYSTIMEDATE;
	ESTATE : AlarmState;
	SEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	ITFTYPEDVALUECURRENT : ITypedValue;
	ITFTYPEDVALUETRIGGER : ITypedValue;
	ITFTYPEDVALUELATCHVAR1 : ITypedValue;
	ITFTYPEDVALUELATCHVAR2 : ITypedValue;
	IOFFSET : INT;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION