FUNCTION SKIPROWS : STO.ERROR
VAR_INPUT
	ITFDATABASEACCESS : IDatabaseAccess;
	IVERSION : INT;
	DISKIPROWS : DINT;
	FILTERCRITERIA : REFERENCE TO VisuFbAlarmFilterCriteria;
END_VAR
VAR_IN_OUT
	BROWIDVALID : BOOL;
	DIROWID : DINT;
END_VAR
END_FUNCTION