FUNCTION IECVARACCBROWSERECURSIVE : SysTypes.RTS_IEC_RESULT
VAR_INPUT
	HINTERFACE : SysTypes.RTS_IEC_HANDLE;
	HNODE : ICollections.IBaseTreeNode;
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PFBROWSECALLBACK : POINTER TO BYTE;
	PUSERPARAMETER : POINTER TO BYTE;
END_VAR
END_FUNCTION