FUNCTION IECVARACCNODEINFOGETBROWSEINFO : POINTER TO RtsBrowseInfo
VAR_INPUT
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PLAST : POINTER TO RtsBrowseInfo;
	PRESULT : POINTER TO SysTypes.RTS_IEC_RESULT;
END_VAR
END_FUNCTION