FUNCTION IECVARACCNODEINFOADDBROWSEINFO : SysTypes.RTS_IEC_RESULT
VAR_INPUT
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PBROWSEINFODATA : POINTER TO RtsBrowseInfo;
END_VAR
END_FUNCTION