FUNCTION IECVARACCGETNODE4 : ICollections.IBaseTreeNode
VAR_INPUT
	PSZPATH : POINTER TO STRING;
	PHINTERFACE : POINTER TO SysTypes.RTS_IEC_HANDLE;
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PRESULT : POINTER TO SysTypes.RTS_IEC_RESULT;
END_VAR
END_FUNCTION