FUNCTION USERMGRGETUSERACCESSRIGHTS : RTS_IEC_RESULT
VAR_INPUT
	PSZOBJECT : REFERENCE TO STRING;
	HUSER : RTS_IEC_HANDLE;
	PULRIGHTS : POINTER TO DWORD;
	PULDENIEDRIGHTS : POINTER TO DWORD;
END_VAR
END_FUNCTION