FUNCTION VISUDLG_PROCESSCHANGESIGN : BOOL
VAR_INPUT
	BPASSWORD : BOOL;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION