FUNCTION VISUDLG_PROCESSCHARW : BOOL
VAR_INPUT
	XPASSWORD : BOOL;
	CTOCONSUME : WSTRING(1);
END_VAR
VAR_IN_OUT
	WSTOUTPUTVALUE : WSTRING;
	WSTVARIABLEVALUE : WSTRING;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION