FUNCTION VISUDLG_PROCESSCHANGENUMBERFORMAT : BOOL
VAR_INPUT
	BPASSWORD : BOOL;
	STCLICKEDRADIO : STRING;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	STMIN : STRING;
	STMAX : STRING;
	IFORMATVALUE : INT;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION