FUNCTION L_SMHP_REGISTERCOMPONENT : RTS_IEC_HANDLE
VAR_INPUT
	COMPTYPE : DWORD;
	LAYER : BYTE;
	XACTIVE : BOOL;
	SCOMPONENTNAME : POINTER TO STRING;
	SINSTANCEPATH : POINTER TO STRING;
	SZREQUESTEDSERVICE : UDINT;
	PREQUESTEDSERVICE : POINTER TO BYTE;
END_VAR
END_FUNCTION