FUNCTION PACKBITSTOWORD : WORD
VAR_INPUT
	XBIT15 : BOOL;
	XBIT14 : BOOL;
	XBIT13 : BOOL;
	XBIT12 : BOOL;
	XBIT11 : BOOL;
	XBIT10 : BOOL;
	XBIT9 : BOOL;
	XBIT8 : BOOL;
	XBIT7 : BOOL;
	XBIT6 : BOOL;
	XBIT5 : BOOL;
	XBIT4 : BOOL;
	XBIT3 : BOOL;
	XBIT2 : BOOL;
	XBIT1 : BOOL;
	XBIT0 : BOOL;
END_VAR
END_FUNCTION