FUNCTION EVENTREGISTERCALLBACK2 : RTS_IEC_HANDLE
VAR_INPUT
	HEVENT : RTS_IEC_HANDLE;
	PICALLBACK : ICmpEventCallback;
	PUSERPARAMETER : POINTER TO BYTE;
END_VAR
VAR_IN_OUT
	RESULT : RTS_IEC_RESULT;
END_VAR
END_FUNCTION