FUNCTION IECVARACCINITVARINFO2 : SysTypes.RTS_IEC_RESULT
VAR_INPUT
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	NSIZEOFVARINFO : UINT;
	HUSER : RTS_IEC_HANDLE;
END_VAR
END_FUNCTION