FUNCTION ABC2R_RAD : BOOL
VAR_INPUT
	A_RAD : LREAL;
	B_RAD : LREAL;
	C_RAD : LREAL;
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
END_VAR
VAR_IN_OUT
	ROTMAT : ARRAY [1..3, 1..3] OF LREAL;
END_VAR
END_FUNCTION