FUNCTION CALCCIRCCENTER2D : BOOL
VAR_OUTPUT
	ALRCENTER : ARRAY [1..2] OF LREAL;
END_VAR
VAR_IN_OUT
	ALRX0 : ARRAY [1..2] OF LREAL;
	ALRX1 : ARRAY [1..2] OF LREAL;
	LRR : LREAL;
	PATHCHOICE : MC_CIRC_PATHCHOICE;
END_VAR
END_FUNCTION