FUNCTION QUAT2ABC_EXTENDED : L_MC4P_ErrorStruct
VAR_INPUT
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
	ALREXPECTEDABC : ARRAY [1..3] OF LREAL;
	AXROTANGLESFIXED : ARRAY [1..3] OF BOOL;
END_VAR
VAR_IN_OUT
	ABC : ARRAY [1..3] OF LREAL;
	QUAT : ARRAY [1..4] OF LREAL;
END_VAR
END_FUNCTION