FUNCTION T2COORD_EXTENDED_FRAME : L_MC4P_ErrorStruct
VAR_INPUT
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
	ALREXPECTEDABC : ARRAY [1..3] OF LREAL;
	AXROTANGLESFIXED : ARRAY [1..3] OF BOOL;
END_VAR
VAR_IN_OUT
	COORDREF : MC_COORD_REF;
	T_01 : L_UMTP_RobotPos;
END_VAR
END_FUNCTION