FUNCTION STRCASECMPA : INT
VAR_INPUT
	PBYTE1 : POINTER TO BYTE;
	PBYTE2 : POINTER TO BYTE;
END_VAR
VAR
	i : DINT;
END_VAR
(* ignoring case (ASCII), the difference of the first bytes that differ — negative when PBYTE1 orders first, 0 when equal *)
IF PBYTE1 = 0 OR PBYTE2 = 0 THEN
	RETURN;
END_IF
WHILE PBYTE1[i] <> 0 AND_THEN CHARTOUPPER(PBYTE1[i]) = CHARTOUPPER(PBYTE2[i]) DO
	i := i + 1;
END_WHILE
STRCASECMPA := BYTE_TO_INT(CHARTOUPPER(PBYTE1[i])) - BYTE_TO_INT(CHARTOUPPER(PBYTE2[i]));
END_FUNCTION