FUNCTION STRLENA : DINT
VAR_INPUT
	PSTDATA : CharBufferPtr;
END_VAR
(* the bytes before the terminator; a null pointer has none *)
IF PSTDATA = 0 THEN
	RETURN;
END_IF
WHILE PSTDATA[STRLENA] <> 0 DO
	STRLENA := STRLENA + 1;
END_WHILE
END_FUNCTION