FUNCTION L_TB2P_TRANSITIONJOGGING : BOOL
VAR_INPUT
	XRTRIGJOGPOS : BOOL;
	XRTRIGJOGNEG : BOOL;
	XJOGPOS : BOOL;
	XJOGNEG : BOOL;
	XQSPAPPLICATION : BOOL;
	XHALT : BOOL;
	XABORT : BOOL;
	EACTTMSTATE : L_TB2P_States;
	DWLIMITERCONTROL : DWORD;
	EALLOWEDDIRECTION : L_TB2P_AllowedDirection;
END_VAR
VAR_OUTPUT
	XDIRECTIONDISABLED : BOOL;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION