FUNCTION L_TB2P_TRANSITIONSYNCIN : BOOL
VAR_INPUT
	XRTRIGSYNCIN : BOOL;
	XSYNCIN : BOOL;
	XJOGPOS : BOOL;
	XJOGNEG : BOOL;
	XQSPAPPLICATION : BOOL;
	EACTTMSTATE : L_TB2P_States;
	DWLIMITERCONTROL : DWORD;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION