FUNCTION L_CT1P_CA_CALCDISTANCE : BOOL
VAR_INPUT
	LRCONSTVELTIME : LREAL;
	LRVELOCITYMAX : LREAL;
	LRACCDECMAX : LREAL;
END_VAR
VAR_OUTPUT
	XERROR : BOOL;
	EERRORID : L_IE1P_Error;
	LRTARGETPOSRELATIVEINT : LREAL;
END_VAR
END_FUNCTION