/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

/* Emptied by hand when the console and gateway were deleted (openspec/changes/sell-cli-subscription).
   The ~300 Resource declarations that were here — ZEN_MODELS1..30, PlanetScale, Upstash, the R2 buckets,
   Honeycomb, Stripe, the OpenAuth issuer, the Api/Console/LogProcessor workers — all belonged to code that
   no longer exists, and nothing imports `sst` at runtime any more: Volt provisions one StaticSite and no
   secrets. `sst deploy` regenerates this file. */

export {}
