FUNCTION PACKBITSTODWORD : DWORD
VAR_INPUT
	XBIT31 : BOOL;
	XBIT30 : BOOL;
	XBIT29 : BOOL;
	XBIT28 : BOOL;
	XBIT27 : BOOL;
	XBIT26 : BOOL;
	XBIT25 : BOOL;
	XBIT24 : BOOL;
	XBIT23 : BOOL;
	XBIT22 : BOOL;
	XBIT21 : BOOL;
	XBIT20 : BOOL;
	XBIT19 : BOOL;
	XBIT18 : BOOL;
	XBIT17 : BOOL;
	XBIT16 : BOOL;
	XBIT15 : BOOL;
	XBIT14 : BOOL;
	XBIT13 : BOOL;
	XBIT12 : BOOL;
	XBIT11 : BOOL;
	XBIT10 : BOOL;
	XBIT9 : BOOL;
	XBIT8 : BOOL;
	XBIT7 : BOOL;
	XBIT6 : BOOL;
	XBIT5 : BOOL;
	XBIT4 : BOOL;
	XBIT3 : BOOL;
	XBIT2 : BOOL;
	XBIT1 : BOOL;
	XBIT0 : BOOL;
END_VAR
END_FUNCTION