FUNCTION STKGETINFO : CS.PROC_STATE
VAR_INPUT
	ECMD : CS.PROC_CMD;
	USINETID : USINT;
	PSTKINFO : POINTER TO CS.STK_INFO;
	PNETINFO : POINTER TO CS.NET_INFO;
END_VAR
VAR_OUTPUT
	EERROR : CS.ERROR;
END_VAR
END_FUNCTION