FUNCTION L_MB1P_HLPCALCKOEFPOLY5THORD : ARRAY [0..5] OF LREAL
VAR_INPUT
	LRYPOSSTART : LREAL;
	LRYVELSTART : LREAL;
	LRYACCSTART : LREAL;
	LRYPOSEND : LREAL;
	LRYVELEND : LREAL;
	LRYACCEND : LREAL;
END_VAR
VAR_OUTPUT
	ALRKOEF : ARRAY [0..5] OF LREAL;
END_VAR
END_FUNCTION