FUNCTION L_MB1P_HLPCALCYOFPOLY5THORDSTATE : LREAL
VAR_INPUT
	LRXPOSSTART : LREAL;
	LRXPOSEND : LREAL := 1;
	LRSETXPOS : LREAL;
	ALRKOEF : ARRAY [0..5] OF LREAL;
END_VAR
VAR_OUTPUT
	LRYPOSSCALED : LREAL;
END_VAR
END_FUNCTION