FUNCTION LOGCOPYINFO : RTS_IEC_RESULT
VAR_INPUT
	HLOGGER : RTS_IEC_HANDLE;
	PSZINFO : POINTER TO STRING;
	PARGLIST : POINTER TO BYTE;
	PSZSTRING : POINTER TO STRING;
	PDIMAXSTRINGLEN : POINTER TO DINT;
END_VAR
END_FUNCTION