FUNCTION L_UMTP_LREQROT : BOOL
VAR_INPUT
	LRA : LREAL;
	LRB : LREAL;
	LRC : LREAL;
	EROTCON : L_UMTP_RotationConvention;
	LRATARGET : LREAL;
	LRBTARGET : LREAL;
	LRCTARGET : LREAL;
	EROTCONTARGET : L_UMTP_RotationConvention;
END_VAR
END_FUNCTION