FUNCTION L_UMTP_ROBOTPOSTIMESROBOTPOS : BOOL
VAR_INPUT
	ROBOTPOSA : REFERENCE TO L_UMTP_RobotPos;
	ROBOTPOSB : REFERENCE TO L_UMTP_RobotPos;
	RESULT : REFERENCE TO L_UMTP_RobotPos;
END_VAR
END_FUNCTION