FUNCTION L_UMTP_MATRIXTIMESMATRIX : BOOL
VAR_INPUT
	PA : POINTER TO LREAL;
	PB : POINTER TO LREAL;
	PRESULT : POINTER TO LREAL;
	ZEILEN_A : __XWORD;
	SPALTEN_A : __XWORD;
	SPALTEN_B : __XWORD;
END_VAR
END_FUNCTION