FUNCTION L_UMTP_MATRIXTIMESVECTOR3DTIMESSKALAR : BOOL
VAR_INPUT
	A : REFERENCE TO L_UMTP_Matrix3x3;
	X : REFERENCE TO L_UMTP_Vector3D;
	SCALAR : LREAL;
	RESULT : REFERENCE TO L_UMTP_Vector3D;
END_VAR
END_FUNCTION