FUNCTION L_UMTP_RESOLVEGIMBALLOCKPOS : BOOL
VAR_INPUT
	PARAM : REFERENCE TO L_UMTP_RotParam;
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
	DPHIAOLD : LREAL;
	DPHIBOLD : LREAL;
	DPHICOLD : LREAL;
	DDPHIAOLD : LREAL;
	DDPHIBOLD : LREAL;
	DDPHICOLD : LREAL;
	T : LREAL;
END_VAR
VAR_OUTPUT
	DPHIACOR : LREAL;
	DPHIBCOR : LREAL;
	DPHICCOR : LREAL;
END_VAR
END_FUNCTION