FUNCTION L_UMTP_ROBOTPOSTIMESFRAMEVEL : BOOL
VAR_INPUT
	ROBOTPOS : REFERENCE TO L_UMTP_RobotPos;
	FRAME : REFERENCE TO L_UMTP_RobotFrame;
	RESULT : REFERENCE TO L_UMTP_RobotFrame;
END_VAR
END_FUNCTION