FUNCTION L_UMTP_DDROT2DDABC : BOOL
VAR_INPUT
	PARAM : REFERENCE TO L_UMTP_RotParam;
	DDROT : REFERENCE TO L_UMTP_Matrix3x3;
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
END_VAR
VAR_OUTPUT
	DDPHIA : LREAL;
	DDPHIB : LREAL;
	DDPHIC : LREAL;
END_VAR
END_FUNCTION