FUNCTION L_UMTP_DORMANDPRINCE45STEP : BOOL
VAR_INPUT
	IODE : L_UMTP_IODE;
	PLRY0 : POINTER TO LREAL;
	UDIDIM : UDINT;
	LRT : LREAL;
	LRH : LREAL;
	LRTOL : LREAL;
END_VAR
VAR_OUTPUT
	LRTNEW : LREAL;
	XACCEPTED : BOOL;
	UDIREPEATS : UDINT;
END_VAR
END_FUNCTION