FUNCTION L_SUDP_WRITEERRORMESSAGE : BOOL
VAR_INPUT
	HLEMACCESS : RTS_IEC_HANDLE;
	SDEVICENAME : STRING;
	WSLAVEADR : WORD;
	TRANSFERTYPE : L_SUDP_TransferType;
	ERRORCODE : L_SUDP_ErrorCodes;
	PSERRORATTACHMENT : POINTER TO STRING;
END_VAR
END_FUNCTION