FUNCTION L_SUDP_GETTARGETVERSION : BOOL
VAR_INPUT
	ETRANSFERTYPE : L_SUDP_TransferType;
	WFIELDBUSMASTERID : WORD;
	WINTERFACE : WORD;
	DNNODEADDRESS : DINT;
	PSTARGETVERSION : POINTER TO STRING(20);
END_VAR
END_FUNCTION