FUNCTION SYSSHAREDMEMORYCREATE : RTS_IEC_HANDLE
VAR_INPUT
	ULPHYSICALADDRESS : __UXINT;
	PULSIZE : POINTER TO __UXINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
VAR_IN_OUT
	PSZNAME : STRING;
END_VAR
END_FUNCTION