FUNCTION TODSPLIT_DAYCHANGECALC : DINT
VAR_INPUT
	TODTIMEHIGH : TIME_OF_DAY;
	TODTIMELOW : TIME_OF_DAY;
	PUIHOUR : UINT;
	PUIMINUTE : UINT;
	PUISECOND : UINT;
	PUIMILLISECOND : UINT;
END_VAR
END_FUNCTION