FUNCTION L_IMHP_GETHIGHESTSEVERITYANDREACTION : BOOL
VAR_INPUT
	ESEVERITY1 : L_IE1P_SeverityLevel;
	EREACTION1 : L_IE1P_Reaction;
	MODULEHANDLER1 : POINTER TO BYTE;
	ESEVERITY2 : L_IE1P_SeverityLevel;
	EREACTION2 : L_IE1P_Reaction;
	MODULEHANDLER2 : POINTER TO BYTE;
END_VAR
VAR_OUTPUT
	ESEVERITY : L_IE1P_SeverityLevel;
	EREACTION : L_IE1P_Reaction;
	MODULEHANDLER : POINTER TO BYTE;
END_VAR
END_FUNCTION