FUNCTION L_IMHP_SIMPLEREGISTERCOMPONENTFORLAM : RTS_IEC_HANDLE
VAR_INPUT
	SCOMPNAME : STRING;
	SPATH : STRING(255);
	UILAYER : UINT;
	UDICOMPTYPE : UDINT;
	UDICOMPSUBTYPE : UDINT;
END_VAR
END_FUNCTION