FUNCTION L_IMHP_EM_NOTIFYERROR : UDINT
VAR_INPUT
	ERRORHANDLERID : RTS_IEC_HANDLE;
	WERRORID : WORD;
	WTEXTREFID : WORD;
	SEVERITY : USINT;
	PRIORITY : USINT;
	GROUP : USINT;
	XNOLOGENTRY : BOOL := FALSE;
END_VAR
END_FUNCTION