FUNCTION L_IMHP_AM_UPDATAASSETINFO : BOOL
VAR_INPUT
	ASSETHANDLE : RTS_IEC_HANDLE;
	DATAID1 : L_IMHP_AM_AssetId;
	UDISIZE1 : UDINT;
	PDATA1 : POINTER TO STRING(255);
	DATAID2 : L_IMHP_AM_AssetId;
	UDISIZE2 : UDINT;
	PDATA2 : POINTER TO STRING(255);
	DATAID3 : L_IMHP_AM_AssetId;
	UDISIZE3 : UDINT;
	PDATA3 : POINTER TO STRING(255);
	DATAID4 : L_IMHP_AM_AssetId;
	UDISIZE4 : UDINT;
	PDATA4 : POINTER TO STRING(255);
	DATAID5 : L_IMHP_AM_AssetId;
	UDISIZE5 : UDINT;
	PDATA5 : POINTER TO STRING(255);
	DATAID6 : L_IMHP_AM_AssetId;
	UDISIZE6 : UDINT;
	PDATA6 : POINTER TO STRING(255);
	DATAID7 : L_IMHP_AM_AssetId;
	UDISIZE7 : UDINT;
	PDATA7 : POINTER TO STRING(255);
	DATAID8 : L_IMHP_AM_AssetId;
	UDISIZE8 : UDINT;
	PDATA8 : POINTER TO STRING(255);
END_VAR
END_FUNCTION