FUNCTION L_RPMA_WRITERECIPE : BOOL
VAR_INPUT
	UISIZERECIPE : UINT;
	XCLEARRECIPE : BOOL;
	XACTIVERECIPE : BOOL;
END_VAR
VAR_IN_OUT
	PBYSELECTEDRECIPE : POINTER TO BYTE;
	PBYACTIVERECIPE : POINTER TO BYTE;
END_VAR
END_FUNCTION