FUNCTION L_MC1P_HLPDELTAVELTIMEEXTENDED : BOOL
VAR_INPUT
	LRVELSTART : LREAL;
	LRACCSTART : LREAL;
	LRMAXACC : LREAL;
	LRMAXJERK : LREAL;
END_VAR
VAR_OUTPUT
	LRTIME : LREAL;
	LRDIST : LREAL;
END_VAR
END_FUNCTION