FUNCTION LOGADD2 : RTS_IEC_RESULT
VAR_INPUT
	HLOGGER : RTS_IEC_HANDLE;
	UDICMPID : UDINT;
	UDICLASSID : UDINT;
	UDIERRORID : UDINT;
	UDIINFOID : UDINT;
	PSZINFO : REFERENCE TO STRING;
END_VAR
END_FUNCTION