FUNCTION L_MB1P_HLPDELTAVELTIMESTATE : BOOL
VAR_INPUT
	LRVELSTART : LREAL;
	LRACCSTART : LREAL;
	LRVELTARGET : LREAL;
	LRACCTARGET : LREAL;
	LRMAXACC : LREAL;
	LRMAXDEC : LREAL;
	LRMAXJERK : LREAL;
END_VAR
VAR_OUTPUT
	LRTIME : LREAL;
	LRDIST : LREAL;
END_VAR
END_FUNCTION