FUNCTION SB_CALCULATEPRODUCTERROR : LREAL
VAR_INPUT
	LRPRODUCTTARGETCORRECTED : LREAL;
	LRMASTERPOSITIONATDETECTION : LREAL;
	LRCORRECTEDFACTORCOMPAREPOSITION : LREAL;
	BYNUMBEROFTARGETS : BYTE;
	LRMASTERCYCLELENGTH : LREAL;
END_VAR
END_FUNCTION