FUNCTION VISU_FCTGETRECIPEDEFINITION2 : DWORD
VAR_INPUT
	DWPARAM1 : __XWORD;
	DWPARAM2 : __XWORD;
	RECIPEMANAGER : IRecipeManager;
	BNOCURRENTRECIPEDEFINITION : BOOL;
END_VAR
VAR_OUTPUT
	_RECIPEDEFINITION : IRecipeDefinition;
END_VAR
END_FUNCTION