FUNCTION VISU_FCTGETRECIPESELECTION : DWORD
VAR_INPUT
	DWPARAM1 : __XWORD;
	DWPARAM2 : __XWORD;
	RECIPEMANAGER : IRecipeManager;
END_VAR
VAR_OUTPUT
	_RECIPEDEFINITION : IRecipeDefinition;
	_RECIPESELECTION : IRecipeSelection;
END_VAR
END_FUNCTION