FUNCTION STRCPYFROM : DINT
VAR_INPUT
	RCBSTARGET : REFERENCE TO CharBufferString;
	RCBSSOURCE : REFERENCE TO CharBufferString;
	DISOURCEOFFSET : DINT;
	DITARGETOFFSET : DINT;
	DICOUNTCHARACTERS : DINT;
END_VAR
END_FUNCTION