FUNCTION STUSPRINTF : INT
VAR_INPUT
	PSTFORMAT : POINTER TO STRING;
	PVARADR : POINTER TO DWORD;
	UDIVARTYPE : __SYSTEM.TYPE_CLASS;
	PBUFFER : POINTER TO BYTE;
	DWBUFFERSIZE : UDINT;
END_VAR
END_FUNCTION