FUNCTION STUSPRINTFW : INT
VAR_INPUT
	WSTFORMAT : POINTER TO WSTRING;
	PVARADR : POINTER TO DWORD;
	UDIVARTYPE : __SYSTEM.TYPE_CLASS;
	PBUFFER : POINTER TO BYTE;
	DWBUFFERSIZE : UDINT;
END_VAR
END_FUNCTION