FUNCTION L_UMTP_APPENDPITCH : BOOL
VAR_INPUT
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
	DDPHIA : LREAL;
	DDPHIB : LREAL;
	DDPHIC : LREAL;
	FRAME : REFERENCE TO L_UMTP_RobotFrame;
END_VAR
END_FUNCTION