FUNCTION L_UMTP_RESOLVEGIMBALLOCKACC : BOOL
VAR_INPUT
	PARAM : REFERENCE TO L_UMTP_RotParam;
	DDPHIA : LREAL;
	DDPHIB : LREAL;
	DDPHIC : LREAL;
	DDPHIAOLD : LREAL;
	DDPHIBOLD : LREAL;
	DDPHICOLD : LREAL;
	T : LREAL;
	XISFIXA : BOOL;
	XISFIXB : BOOL;
	XISFIXC : BOOL;
END_VAR
VAR_OUTPUT
	DDPHIACOR : LREAL;
	DDPHIBCOR : LREAL;
	DDPHICCOR : LREAL;
END_VAR
END_FUNCTION