FUNCTION L_UMTP_POLY5COEFFS : BOOL
VAR_INPUT
	LRY0 : LREAL;
	LRY1 : LREAL;
	LRDY0 : LREAL;
	LRDY1 : LREAL;
	LRDDY0 : LREAL;
	LRDDY1 : LREAL;
	LRL : LREAL;
END_VAR
VAR_OUTPUT
	LRA0 : LREAL;
	LRA1 : LREAL;
	LRA2 : LREAL;
	LRA3 : LREAL;
	LRA4 : LREAL;
	LRA5 : LREAL;
END_VAR
END_FUNCTION