FUNCTION L_UMTP_FADFRAME : BOOL
VAR_INPUT
	LRFADFACTOR : LREAL;
END_VAR
VAR_IN_OUT
	SCFRAME : L_UMTP_RobotFrame;
	SCROTVECTOR : L_UMTP_Vector3D;
	SCFRAMEFADED : L_UMTP_RobotFrame;
	SCROTVECTORFADED : L_UMTP_Vector3D;
END_VAR
END_FUNCTION