FUNCTION GETTEXT : ReturnValues
VAR_INPUT
	PSTEXT : POINTER TO STRING;
	DISIZE : DINT;
END_VAR
VAR_OUTPUT
	BDEFAULTTEXT : BOOL;
END_VAR
VAR_IN_OUT
	STEXTLIST : STRING;
	STEXTINDEX : STRING;
END_VAR
END_FUNCTION