FUNCTION OPENLOGINDIALOG3 : BOOL
VAR_INPUT
	PCLIENTDATA : POINTER TO VisuElems.VisuStructClientData;
	ITFVISUALELEMENT : VisuElems.IVisualElement;
	PPOSITION : POINTER TO VisuElems.VisuStructSimpleRectangle;
END_VAR
END_FUNCTION