PROGRAM Status_ForceOutputs
VAR
END_VAR

NETWORK 0 LD
  LET g9 := TRUE;
  MOVE(g9, %IB26);
  MOVE(g9, %IB27);
END_NETWORK
NETWORK 1 LD
  LET g13 := TRUE;
  MOVE(g13, %IB370);
  MOVE(g13, %IB371);
  MOVE(g13, %IB372);
  MOVE(g13, %IB373);
END_NETWORK
NETWORK 2 LD
  ForceOutput(HMI_Var.ForceOutputs);
END_NETWORK
NETWORK 3 LD
  ForceOutput_1(NOT HMI_Var.ForceOutputs);
END_NETWORK
NETWORK 4 LD
END_NETWORK

END_PROGRAM
