FUNCTION RECIPEDODATASOURCESEXCHANGE : UDINT
VAR_INPUT
	VARIABLES : RecipeRemoteVariables;
	BWRITING : BOOL;
	RECIPEMANAGER : IRecipeManager;
	DATASOURCESMGR : IDatasources.IDatasourcesMgr;
END_VAR
END_FUNCTION