FUNCTION RECIPEDODATASOURCESEXCHANGE2 : UDINT
VAR_INPUT
	VARIABLES : RecipeRemoteVariables;
	RECIPEDEFNAME : STRING;
	BWRITING : BOOL;
	RECIPEMANAGER : IRecipeManager;
	DATASOURCESMGR : IDatasources.IDatasourcesMgr;
END_VAR
END_FUNCTION