FUNCTION ISSPACECHARACTER : BOOL
VAR_INPUT
	WCHARACTER : WORD;
END_VAR
(* a space, or one of the control characters TAB, LF, VT, FF, CR *)
ISSPACECHARACTER := WCHARACTER = 16#20 OR (WCHARACTER >= 16#09 AND WCHARACTER <= 16#0D);
END_FUNCTION