FUNCTION WCHARTOUPPER : WORD
VAR_INPUT
	WDCHAR : WORD;
END_VAR
(* ASCII only, as CharToUpper: a..z become A..Z, every other unit is itself *)
IF WDCHAR >= 16#61 AND WDCHAR <= 16#7A THEN
	WCHARTOUPPER := WDCHAR - 16#20;
ELSE
	WCHARTOUPPER := WDCHAR;
END_IF
END_FUNCTION