FUNCTION L_IF1P_GETIOMGRCONFIGGETFIRSTCONNECTOR : POINTER TO IoConfigConnector
VAR_INPUT
	PIOCONNECTORLIST : POINTER TO IoConfigConnector;
	PNCOUNT : POINTER TO DINT;
	WTYPE : WORD;
END_VAR
END_FUNCTION