FUNCTION ASYNCADD : RTS_IEC_HANDLE
VAR_INPUT
	PFJOBFUNC : POINTER TO BYTE;
	PPARAM : POINTER TO BYTE;
	PINSTANCE : POINTER TO BYTE;
	PULSTATE : POINTER TO UDINT;
	ULIECFUNC : UDINT;
	ULTYPE : UDINT;
	ULTIMEOUT : UDINT;
	PASYNCJOBPARAM : POINTER TO ASYNCJOB_PARAM;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION