FUNCTION SPLITDATETIME : ERROR
VAR_INPUT
	ULIDATETIME : ULINT;
END_VAR
VAR_OUTPUT
	UIYEAR : YEAR;
	UIMONTH : MONTH;
	UIDAY : DAY;
	UIHOUR : HOUR;
	UIMINUTE : MINUTE;
	UISECOND : SECOND;
	UIMILLISECONDS : MILLISECOND;
	EWEEKDAY : WEEKDAY;
END_VAR
END_FUNCTION