#!/usr/bin/env python3
"""
Bundle CodesysBridge into a single self-contained .py file.

CODESYS's `Tools > Scripting > Execute Script File` takes ONE file —
the user picks one path and CODESYS runs it. Our development tree
has many modules for clarity (handlers/, helpers/, etc.). This
script produces a single concatenated `volt-codesys-bridge.py` for
distribution while keeping the source modular for development.

Approach: each source module's content is base64-encoded and embedded
as a string literal in the bundle. A small bootstrap at the top of
the bundle decodes each, builds a `types.ModuleType` for it, and
registers it in `sys.modules`. The existing `import` statements in
the bridge code then resolve to the bundled modules — NO source
rewrites required, NO escape-hazard with triple-quoted docstrings.

Stack traces stay useful: the bootstrap also injects each module's
source into `linecache` so a traceback inside, say, push.py shows
the right source line.

Output: `dist/volt-codesys-bridge.py`.

Run:
  python bundle.py
or (called from the monorepo build):
  bash packages/volt-bridges/build-bridges.sh   # calls bundle.py automatically
"""
import base64
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_ROOT = os.path.join(HERE, "CodesysBridge")
DIST_DIR = os.path.join(os.path.dirname(HERE), "dist")
OUT_PATH = os.path.join(DIST_DIR, "volt-codesys-bridge.py")
VERSION_PATH = os.path.join(SRC_ROOT, "version.json")

# Module load order — leaves before nodes that depend on them.
# Each entry: (full module name, path relative to SRC_ROOT)
MODULES = [
	("CodesysBridge", "__init__.py"),
	("CodesysBridge.helpers", "helpers/__init__.py"),
	("CodesysBridge.handlers", "handlers/__init__.py"),
	("CodesysBridge.helpers.compat", "helpers/compat.py"),
	("CodesysBridge.helpers.log", "helpers/log.py"),
	("CodesysBridge.helpers.json_lite", "helpers/json_lite.py"),
	("CodesysBridge.helpers.block_type_mapper", "helpers/block_type_mapper.py"),
	("CodesysBridge.helpers.plcopen_xml", "helpers/plcopen_xml.py"),
	("CodesysBridge.helpers.cross_bundle_state", "helpers/cross_bundle_state.py"),
	("CodesysBridge.helpers.code_helper", "helpers/code_helper.py"),
	("CodesysBridge.helpers.st_splitter", "helpers/st_splitter.py"),
	("CodesysBridge.helpers.st_assembler", "helpers/st_assembler.py"),
	("CodesysBridge.ui_thread", "ui_thread.py"),
	("CodesysBridge.codesys_connection", "codesys_connection.py"),
	# Type-extension registry — loaded BEFORE the handlers that
	# consume it (fetch, refs, push). Pure-Python module with no
	# scripting-engine imports of its own; safe to load early.
	("CodesysBridge.handlers.extensions", "handlers/extensions.py"),
	("CodesysBridge.handlers.health", "handlers/health.py"),
	("CodesysBridge.handlers.refs", "handlers/refs.py"),
	("CodesysBridge.handlers.fetch", "handlers/fetch.py"),
	("CodesysBridge.handlers.push", "handlers/push.py"),
	("CodesysBridge.handlers.build", "handlers/build.py"),
	("CodesysBridge.handlers.debug", "handlers/debug.py"),
]
ENTRY_REL = "bridge.py"

# Modules whose name is a package (have __path__) — these get marked
# as packages in sys.modules so submodule imports work.
PACKAGE_MODULES = frozenset([
	"CodesysBridge",
	"CodesysBridge.helpers",
	"CodesysBridge.handlers",
])


PREAMBLE_TEMPLATE = '''#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Volt CODESYS Bridge — single-file bundle (auto-generated).

DO NOT EDIT THIS FILE. It is generated by
packages/volt-bridges/codesys/bundle.py from the source modules in
packages/volt-bridges/codesys/CodesysBridge/. Edit those and rebuild.

Bundle version: {version}
Bundled modules: {module_count}

Usage in CODESYS V3.5 SP19+:
  Tools > Scripting > Execute Script File > select this file.
The bridge boots an HTTP server on http://127.0.0.1:8556 (override
via VOLT_BRIDGE_PORT env var).
"""
import base64
import linecache
import sys
import types


def _install_bundled_module(fullname, source_b64, is_package=False):
    """Decode a base64-embedded source module and register it in
    sys.modules so subsequent `import` statements find it without
    any filesystem lookup. Also injects the source into linecache
    so tracebacks show usable source lines."""
    parts = fullname.split(".")
    # Ensure parent packages exist (the bundler emits them in order
    # so this is normally a no-op, but defensive in case order shifts).
    for i in range(1, len(parts)):
        parent = ".".join(parts[:i])
        if parent not in sys.modules:
            pmod = types.ModuleType(parent)
            pmod.__path__ = []
            pmod.__package__ = parent
            sys.modules[parent] = pmod

    src_bytes = base64.b64decode(source_b64)
    try:
        src = src_bytes.decode("utf-8")
    except Exception:
        src = src_bytes.decode("latin-1")

    mod = types.ModuleType(fullname)
    # Windows-path-safe pseudo-path. The angle-bracket/colon form
    # Python normally uses for synthetic modules ("<bundled:X>")
    # makes CODESYS's debugger spam "Illegal characters in path"
    # when its line tracer tries to load source.
    fake_path = "bundled_" + fullname.replace(".", "_") + ".py"
    mod.__file__ = fake_path
    if is_package:
        mod.__path__ = []
        mod.__package__ = fullname
    elif "." in fullname:
        mod.__package__ = fullname.rsplit(".", 1)[0]
    else:
        mod.__package__ = fullname

    # Inject source lines into linecache so tracebacks resolve to
    # readable code instead of "<no source>".
    src_lines = src.splitlines(True)
    linecache.cache[fake_path] = (len(src), None, src_lines, fake_path)

    sys.modules[fullname] = mod
    exec(compile(src, fake_path, "exec"), mod.__dict__)
    return mod


# ---------------------------------------------------------------------
# Bundled modules — load order matters (leaves before nodes that use them).
# ---------------------------------------------------------------------
'''


def main():
	if not os.path.isdir(DIST_DIR):
		os.makedirs(DIST_DIR)

	with open(VERSION_PATH) as fh:
		version = json.load(fh)["version"]

	out = []
	out.append(PREAMBLE_TEMPLATE.format(version=version, module_count=len(MODULES)))

	for (fullname, relpath) in MODULES:
		path = os.path.join(SRC_ROOT, relpath)
		with open(path, "rb") as fh:
			raw = fh.read()
		b64 = base64.b64encode(raw).decode("ascii")
		is_pkg = fullname in PACKAGE_MODULES
		# Chunk the base64 string to ~70 char lines for readable diffs.
		# Empty source (e.g. empty __init__.py) → single empty string
		# so the emitted second arg is `""`, not nothing.
		if not b64:
			joined = '""'
		else:
			chunks = [b64[i: i + 70] for i in range(0, len(b64), 70)]
			joined = "\n    ".join(repr(c) for c in chunks)
		out.append(
			"_install_bundled_module(\n"
			"    {fullname!r},\n"
			"    {joined},\n"
			"    is_package={is_pkg!r},\n"
			")".format(fullname=fullname, joined=joined, is_pkg=is_pkg)
		)

	# Append the entry-point's source after a separator. The entry is
	# NOT registered as a module — we just exec its top-level so
	# bridge.main() runs the server.
	entry_path = os.path.join(SRC_ROOT, ENTRY_REL)
	with open(entry_path, "r", encoding="utf-8") as fh:
		entry_src = fh.read()

	# Strip the entry's own sys.path manipulation — irrelevant after
	# bundling — and the `from CodesysBridge import ...` lines (they
	# resolve via sys.modules already, but we keep them for clarity).
	# Actually: leave the entry source as-is. The imports work because
	# we pre-populated sys.modules above. The sys.path inserts are
	# harmless when run as a single file.

	out.append("\n# " + "=" * 70)
	out.append("# Entry point -- runs bridge.main() to start the HTTP server.")
	out.append("# " + "=" * 70)
	# Inject the version so the entry's _read_bridge_version() finds it
	# without needing version.json on the filesystem.
	out.append("_BUNDLED_VERSION = {0!r}\n".format(version))
	# Unique build-id per bundle invocation, so /health can reveal
	# exactly which bundle is running. Critical for diagnosing "did my
	# re-execution actually take over the old bridge?" — same
	# _BUNDLED_VERSION every time would tell us nothing.
	import datetime, hashlib
	stamp = datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
	# Hash the bundled source so identical rebuilds produce identical
	# ids (idempotent), but ANY source change produces a new id.
	content_so_far = "\n\n".join(out)
	digest = hashlib.sha1(content_so_far.encode("utf-8")).hexdigest()[:8]
	build_id = "{0}-{1}".format(stamp, digest)
	out.append("_BUNDLED_BUILD_ID = {0!r}\n".format(build_id))
	out.append(entry_src)

	# Write atomically.
	tmp_path = OUT_PATH + ".tmp"
	with open(tmp_path, "w", encoding="utf-8", newline="\n") as fh:
		fh.write("\n\n".join(out))
		if not fh.tell() or not out[-1].endswith("\n"):
			fh.write("\n")
	os.replace(tmp_path, OUT_PATH)

	size_kb = os.path.getsize(OUT_PATH) / 1024.0
	print("wrote {0} ({1:.1f} KB, {2} bundled modules)".format(OUT_PATH, size_kb, len(MODULES)))


if __name__ == "__main__":
	main()
