FUNCTION L_SEMP_GETCOMMANDEVENTREACTIONPARAMETER : BOOL
VAR_INPUT
	PPARAMETER : POINTER TO BYTE;
	SEVERITY : POINTER TO USINT;
	EVENTID : POINTER TO WORD;
	TEXTREFID : POINTER TO WORD;
END_VAR
END_FUNCTION