FUNCTION L_SEMP_NOTIFYEVENT_V2 : RTS_IEC_RESULT
VAR_INPUT
	HHANDLE : RTS_IEC_HANDLE := RTS_INVALID_HANDLE;
	UIEVENTID : UINT := 16#0;
	ESEVERITY : USINT := L_SEMP_Serverity.LEM_SEV_NO_RESPONSE;
	UITEXTREFID : UINT := 16#0;
	UINUMPARAM : UINT := 16#0;
	PPARAMETES : POINTER TO L_SEMP_EventParameters;
	UIEVENTCONTROL : UINT := 16#0;
	UIUSERPRIORITY : UINT := 16#0;
	UITARGETGROUP : UINT := 16#0;
END_VAR
END_FUNCTION