FUNCTION VISHCLIENTGETINFO : INT
VAR_INPUT
	DWEXTERNID : DWORD;
	PTAGS : POINTER TO Visu_ClientTagData;
	ISZTAGS : INT;
END_VAR
VAR_OUTPUT
	DWCREATIONFLAGS : DWORD;
	INUMTAGS : INT;
END_VAR
END_FUNCTION