FUNCTION L_UMTP_DDABC2DDROT : BOOL
VAR_INPUT
	PARAM : L_UMTP_RotParam;
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
	DDPHIA : LREAL;
	DDPHIB : LREAL;
	DDPHIC : LREAL;
	DDROT : REFERENCE TO L_UMTP_Matrix3x3;
END_VAR
END_FUNCTION