FUNCTION L_UMTP_THOMASALGORITHM : BOOL
VAR_INPUT
	IDIM : INT;
	ALRA : POINTER TO LREAL;
	ALRD : POINTER TO LREAL;
	ALRX : POINTER TO LREAL;
END_VAR
VAR_OUTPUT
	XERROR : BOOL := FALSE;
	EERRORID : L_IE1P_Error := L_IE1P_Error.NoError;
END_VAR
END_FUNCTION