FUNCTION L_UMTP_FRAMETIMESROBOTPOSVEL : BOOL
VAR_INPUT
	FRAME : REFERENCE TO L_UMTP_RobotFrame;
	ROBOTPOS : REFERENCE TO L_UMTP_RobotPos;
	RESULT : REFERENCE TO L_UMTP_RobotFrame;
END_VAR
END_FUNCTION