FUNCTION L_UMTP_CHECKSTEPSIZE : BOOL
VAR_INPUT
	PLRY0 : POINTER TO LREAL;
	PLRY1 : POINTER TO LREAL;
	UDIDIM : UDINT;
	LRTOL : LREAL;
	LRH : LREAL;
END_VAR
VAR_OUTPUT
	LRHTOL : LREAL;
END_VAR
END_FUNCTION