FUNCTION L_UMTP_FINDINTERVAL : BOOL
VAR_INPUT
	LRVALUE : LREAL;
	PLRVALUES : POINTER TO LREAL;
	NDATA : UDINT;
	NSTRIDE : UDINT;
	XTRYFIRST : BOOL;
END_VAR
VAR_OUTPUT
	XERROR : BOOL;
	EERRORID : L_IE1P_Error;
END_VAR
VAR_IN_OUT
	UDIINTERVAL : UDINT;
END_VAR
END_FUNCTION