FUNCTION L_UMTP_REDUCEPITCH : BOOL
VAR_INPUT
	FRAME : REFERENCE TO L_UMTP_RobotFrame;
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
END_VAR
VAR_OUTPUT
	DDPHIA : LREAL;
	DDPHIB : LREAL;
	DDPHIC : LREAL;
END_VAR
END_FUNCTION