FUNCTION CRC16_GENERIC : WORD
VAR_INPUT
	PMEMORYBLOCK : POINTER TO BYTE;
	UILENGTH : UINT;
	WCRCINIT : WORD;
	WPOLY : WORD;
	XREFLECTINPUT : BOOL;
	XREFLECTOUTPUT : BOOL;
	WXOROUT : WORD;
END_VAR
END_FUNCTION