FUNCTION CALLGLUEDESERIALIZEPARAMETERS : RTS_IEC_RESULT
VAR_INPUT
	PARGUMENTBUFFER : POINTER TO BYTE;
	NARGUMENTBUFFERSIZE : __XWORD;
	ITYPEDESC : REFERENCE TO TypeDesc;
	PPARSEDARGUMENTS : POINTER TO BYTE;
	NPARSEDARGUMENTSIZE : __XWORD;
END_VAR
END_FUNCTION