FUNCTION SYSSOCKGETOPTION : RTS_IEC_RESULT
VAR_INPUT
	HSOCKET : RTS_IEC_HANDLE;
	DILEVEL : DINT;
	DIOPTION : DINT;
	PDIOPTIONVALUE : POINTER TO DINT;
	PDIOPTIONLEN : POINTER TO DINT;
END_VAR
END_FUNCTION