FUNCTION SYSSOCKSENDTOUDP : __XINT
VAR_INPUT
	HSOCKETUDP : RTS_IEC_HANDLE;
	DIPORT : DINT;
	SZDESTADDRESS : REFERENCE TO STRING;
	PBYDATA : POINTER TO BYTE;
	DIDATASIZE : __XINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION