FUNCTION SYSPROCESSEXECUTECOMMAND2 : DINT
VAR_INPUT
	PSZCOMMAND : REFERENCE TO STRING;
	PSZSTDOUT : REFERENCE TO STRING;
	UDISTDOUTLEN : UDINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION