FUNCTION SYSPROCESSCREATE : RTS_IEC_HANDLE
VAR_INPUT
	PSZAPPLICATION : REFERENCE TO STRING;
	PSZCOMMANDLINE : REFERENCE TO STRING;
	ULHIDE : UDINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION