FUNCTION GETLANGUAGETEXTW : ReturnValues
VAR_INPUT
	PWSTEXT : POINTER TO WSTRING;
	DISIZE : DINT;
END_VAR
VAR_OUTPUT
	BDEFAULTTEXT : BOOL;
END_VAR
VAR_IN_OUT
	STEXTLIST : STRING;
	STEXTINDEX : STRING;
	SLANGUAGE : STRING;
END_VAR
END_FUNCTION