FUNCTION L_TB2P_TRANSITIONMOVEPROFILE : BOOL
VAR_INPUT
	XRTRIGMOVEPROFILE : BOOL;
	XMOVEPROFILE : BOOL;
	IPROFILEDIRECTION : INT := 0;
	XJOGPOS : BOOL;
	XJOGNEG : BOOL;
	XQSPAPPLICATION : BOOL;
	EACTTMSTATE : L_TB2P_States;
	DWLIMITERCONTROL : DWORD;
	EALLOWEDDIRECTION : L_TB2P_AllowedDirection;
END_VAR
VAR_OUTPUT
	XDIRECTIONDISABLED : BOOL;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION