FUNCTION CONFIGGETNEXTCHILD : POINTER TO IoConfigConnector
VAR_INPUT
	PIOCONNECTORLIST : POINTER TO IoConfigConnector;
	PNCOUNT : POINTER TO DINT;
	PFATHER : POINTER TO IoConfigConnector;
END_VAR
END_FUNCTION