FUNCTION L_SUDP_WRITELOGMESSAGE : BOOL
VAR_INPUT
	HLEMACCESS : RTS_IEC_HANDLE;
	SDEVICENAME : STRING;
	WSLAVEADR : WORD;
	TRANSFERTYPE : L_SUDP_TransferType;
	LOGCLASS : UDINT;
	UDILOGID : UDINT;
	PSLOGMESSAGE : POINTER TO STRING;
END_VAR
END_FUNCTION