FUNCTION VISUDLGUTIL_CLOSENUMPADEXTENDED : BOOL
VAR_INPUT
	FLAGS : DWORD;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	STMIN : STRING;
	STMAX : STRING;
	IFORMATVALUE : INT;
	BINITFORMATVALUE : BOOL;
END_VAR
END_FUNCTION