FUNCTION VISUDLG_CHECKEDCHANGESIGNEXTENDED : BOOL
VAR_INPUT
	BPASSWORD : BOOL;
	IFORMATVALUE : INT;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	BINIT : BOOL;
END_VAR
END_FUNCTION