FUNCTION VISUDLG_PROCESSCHAR : BOOL
VAR_INPUT
	XPASSWORD : BOOL;
	CTOCONSUME : STRING(4);
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION