FUNCTION VISUDLG_PROCESSCLEAR : BOOL
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	FLAGS : DWORD;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION