FUNCTION VISUDLG_CHECKEDAPPENDW : BOOL
VAR_INPUT
	BPASSWORD : BOOL;
	CTOAPPEND : WSTRING(1);
END_VAR
VAR_IN_OUT
	WSTOUTPUTVALUE : WSTRING;
	WSTVARIABLEVALUE : WSTRING;
	BINIT : BOOL;
END_VAR
END_FUNCTION