FUNCTION VISHWRITEVALUEIFVALID : INT
VAR_INPUT
	PSTTOWRITE : POINTER TO STRING;
	PDATATOWRITETO : POINTER TO BYTE;
	DATATYPE : Visu_Types;
	PINPUTCHECKS : POINTER TO Visu_InputChecks;
END_VAR
END_FUNCTION