FUNCTION IECVARACCGETNODEFULLPATH4 : DINT
VAR_INPUT
	HINTERFACE : SysTypes.RTS_IEC_HANDLE;
	HNODE : ICollections.IBaseTreeNode;
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PSZPATH : POINTER TO STRING;
	IMAXPATH : DINT;
	PRESULT : POINTER TO SysTypes.RTS_IEC_RESULT;
END_VAR
END_FUNCTION