FUNCTION L_UBUP_QUERY_IJOB_ALL : BOOL
VAR_INPUT
	ITFJOB : L_UBUP_IJob;
END_VAR
VAR_OUTPUT
	ITFINSTANCE : L_UBUP_IPoolInstance;
	ITFSTATECLIENT : L_UBUP_IStateClient;
	ITFPLCOPENSTATUS : L_UBUP_IPLCOpenStatus;
END_VAR
END_FUNCTION