FUNCTION L_SUDP_WRITESUCCESSMESSAGE : BOOL
VAR_INPUT
	HLEMACCESS : RTS_IEC_HANDLE;
	SDEVICENAME : STRING;
	WSLAVEADR : WORD;
	TRANSFERTYPE : L_SUDP_TransferType;
	SUCCESSCODE : L_SUDP_SuccessCodes;
	PSATTACHEDTXT : POINTER TO STRING;
END_VAR
END_FUNCTION