FUNCTION CALCTXPDOOFFSETS131 : BOOL
VAR_INPUT
	PCONNECTOR : POINTER TO IoConfigConnector;
	WSLICEPOSITION : WORD;
	WPDOOFFSETBASE : WORD;
END_VAR
VAR_OUTPUT
	WPDOOFFSET : WORD;
	WPDONUMBEROFENTRIES : WORD;
END_VAR
END_FUNCTION