FUNCTION FINDOWNSLICEPOSITIONS131 : BOOL
VAR_INPUT
	M_HINTERFACE : POINTER TO IoConfigConnector;
	M_PCONNECTOR : POINTER TO IoConfigConnector;
	WMODULETYPE : WORD;
END_VAR
VAR_OUTPUT
	WSLICEPOSITION : WORD;
END_VAR
END_FUNCTION