FUNCTION L_UBUP_GETTASKINFO : BOOL
VAR_OUTPUT
	ITASKINDEX : INT;
	HTASK : RTS_IEC_HANDLE;
	HIECTASK : RTS_IEC_HANDLE;
	PSCSYSTASKINFO : POINTER TO SYS_TASK_INFO;
	UDIOSPRIORITY : UDINT;
	UDIPRIORITY : UDINT;
	UDITASKINTERVAL : UDINT;
END_VAR
END_FUNCTION