FUNCTION L_UBUP_LOCALDATEANDTIME : BOOL
VAR_OUTPUT
	UIYEAR : UINT;
	UIMONTH : UINT;
	UIDAY : UINT;
	UIHOUR : UINT;
	UIMINUTE : UINT;
	UISECOND : UINT;
	UIMILLISECONDS : UINT;
	UIWEEKDAY : UINT;
	DATDATE : DATE;
	TODTIME : TIME_OF_DAY;
END_VAR
END_FUNCTION