FUNCTION USERMGRCHANGEMYPASSWORD : RTS_IEC_RESULT
VAR_INPUT
	HUSER : RTS_IEC_HANDLE;
	PSZUSER : REFERENCE TO STRING;
	PSZOLDPASSWORD : REFERENCE TO STRING;
	PSZNEWPASSWORD : REFERENCE TO STRING;
END_VAR
END_FUNCTION