FUNCTION USERMGRUSERGETNEXTINTERNAL : RTS_IEC_RESULT
VAR_INPUT
	HUSER : RTS_IEC_HANDLE;
	IMAXLEN : UDINT;
END_VAR
VAR_OUTPUT
	USERPROPERTY : DWORD;
END_VAR
VAR_IN_OUT
	PHITERATOR : RTS_IEC_HANDLE;
	PSZUSERNAME : STRING;
END_VAR
END_FUNCTION