FUNCTION IOMGRREADPARAMETER : UDINT
VAR_INPUT
	DWMODULETYPE : DWORD;
	DWINSTANCE : DWORD;
	DWPARAMETERID : DWORD;
	PDATA : POINTER TO BYTE;
	DWBITSIZE : DWORD;
	DWBITOFFSET : DWORD;
END_VAR
END_FUNCTION