FUNCTION IOMGRCONFIGGETCONNECTOR : POINTER TO IoConfigConnector
VAR_INPUT
	PCONNECTORLIST : POINTER TO IoConfigConnector;
	PNCOUNT : POINTER TO DINT;
	DWMODULETYPE : DWORD;
	DWINSTANCE : DWORD;
END_VAR
END_FUNCTION