FUNCTION IECVARACCGETNODENAME4 : SysTypes.RTS_IEC_RESULT
VAR_INPUT
	HINTERFACE : SysTypes.RTS_IEC_HANDLE;
	HNODE : ICollections.IBaseTreeNode;
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PSZNODENAME : POINTER TO STRING;
	NNODENAMELEN : UDINT;
END_VAR
END_FUNCTION