FUNCTION IECVARACCNODEINFOGETREFERENCE : POINTER TO BYTE
VAR_INPUT
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PRESULT : POINTER TO SysTypes.RTS_IEC_RESULT;
END_VAR
END_FUNCTION