FUNCTION IECVARACCNODEINFOADDREFERENCE : SysTypes.RTS_IEC_RESULT
VAR_INPUT
	PVARIABLEINFORMATION : POINTER TO IecVarAccess_Interfaces.VariableInformationStruct3;
	PREFERENCEINFODATA : POINTER TO BYTE;
	NINFOSIZE : XWORD;
	PNEWREFERENCEINFO : POINTER TO POINTER TO BYTE;
END_VAR
END_FUNCTION