FUNCTION MAPCOMMENT : BOOL
VAR_INPUT
	ALARM : IAlarm5;
	ESTATE : AlarmState;
END_VAR
VAR_OUTPUT
	COMMENT : OpcUa_LocalizedText;
	USERID : OpcUa_String;
	PCOMMENT : POINTER TO WSTRING;
	PUSERID : POINTER TO WSTRING;
END_VAR
VAR_IN_OUT
	COMMENTBUFFER : ARRAY [0..512] OF BYTE;
	USERIDBUFFER : ARRAY [0..512] OF BYTE;
END_VAR
END_FUNCTION