FUNCTION CODEMENCRYPT : RTS_IEC_RESULT
VAR_INPUT
	HCODEMETER : RTS_IEC_HANDLE;
	UDIENCRYPTIONCODE : UDINT;
	PBYDATA : POINTER TO BYTE;
	NDATALEN : __XWORD;
END_VAR
VAR_IN_OUT
	ULCRC : UDINT;
END_VAR
END_FUNCTION