FUNCTION SYSTASKCREATE2 : RTS_IEC_HANDLE
VAR_INPUT
	PSZTASKNAME : REFERENCE TO STRING;
	PFUNCTION : PFSYS_TASK_FUNCTION;
	PPARAM : POINTER TO SYS_TASK_PARAM;
	ULPRIORITY : UDINT;
	ULINTERVAL : UDINT;
	ULSTACKSIZE : UDINT;
	PEXCEPTIONHANDLER : PFSYS_TASK_EXCEPTIONHANDLER;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION