FUNCTION SYSTASKCREATE : RTS_IEC_RESULT
VAR_INPUT
	PSZTASKNAME : REFERENCE TO STRING;
	PFUNCTION : PFSYS_TASK_FUNCTION;
	PPARAM : POINTER TO SYS_TASK_PARAM;
	ULPRIORITY : UDINT;
	ULINTERVAL : UDINT;
	ULSTACKSIZE : UDINT;
	PEXCEPTIONHANDLER : PFSYS_TASK_EXCEPTIONHANDLER;
	PHTASKHANDLE : POINTER TO RTS_IEC_HANDLE;
END_VAR
END_FUNCTION