FUNCTION USERMGROBJECTGETGROUPRIGHTS : RTS_IEC_RESULT
VAR_INPUT
	HUSER : RTS_IEC_HANDLE;
	HOBJECT : RTS_IEC_HANDLE;
	HGROUP : RTS_IEC_HANDLE;
END_VAR
VAR_OUTPUT
	ULRIGHTS : DWORD;
	ULDENIEDRIGHTS : DWORD;
END_VAR
END_FUNCTION