FUNCTION USERMGRGROUPGETFIRSTUSER : RTS_IEC_RESULT
VAR_INPUT
	HUSER : RTS_IEC_HANDLE;
	HGROUP : RTS_IEC_HANDLE;
END_VAR
VAR_IN_OUT
	PHITERATOR : RTS_IEC_HANDLE;
	PSZUSERNAME : STRING(59);
END_VAR
END_FUNCTION