FUNCTION _PRINTF : BOOL
VAR_INPUT
	CBPRESULT : CharBufferPtr;
	UIRESULTCAPACITY : UINT;
	STRINGTYPE : __SYSTEM.TYPE_CLASS;
	CBPFORMAT : CharBufferPtr;
	PVALUE : POINTER TO BYTE;
	TYPECLASS : __SYSTEM.TYPE_CLASS;
END_VAR
END_FUNCTION