FUNCTION SETTGGETWSTRINGVALUE : RTS_IEC_RESULT
VAR_INPUT
	PSZCOMPONENT : REFERENCE TO STRING;
	PSZKEY : REFERENCE TO STRING;
	PWSZVALUE : POINTER TO WSTRING;
	PILEN : POINTER TO DINT;
	PWSZDEFAULT : REFERENCE TO WSTRING;
	BCACHED : DINT;
END_VAR
END_FUNCTION