FUNCTION BUILDANDENQUEUEV3REQUEST : UDINT
VAR_INPUT
	ITFDATASOURCE : IDatasources.IDatasource;
	ITFCDSV3REQUESTBUILDER : ICDSV3RequestBuilder;
	ITFREQUESTCALLBACK : IDatasources.ICustomRequestCallback;
END_VAR
VAR_OUTPUT
	EREMOTEBYTEORDER : IDatasources.ByteOrder;
	XHASTOSWAP : BOOL;
	ITFCDSV3REQUEST : IDatasources.ICDSV3Request;
END_VAR
END_FUNCTION