FUNCTION APPCALLSETPROPERTY2 : RTS_IEC_RESULT
VAR_INPUT
	PINSTANCE : POINTER TO BYTE;
	PPSETMETHOD : POINTER TO POINTER TO BYTE;
	PBYVALUE : POINTER TO BYTE;
	ULSIZE : __XWORD;
	ULOFFSET : __XWORD;
END_VAR
END_FUNCTION