FUNCTION VISUINPUT_CHECKUPDATEELEMENTSTATEPOSSIBLE_DEPENDINGONCURRENTINPUT : BOOL
VAR_INPUT
	IVE : IVisualElement;
	PINPUT2 : POINTER TO VisuFbInputBase2;
	IELEMNR : DINT;
	PCURRENTCLIENTDATA : POINTER TO VisuStructClientData;
END_VAR
END_FUNCTION