FUNCTION BTAGWRITERSWITCHBUFFER : RTS_IEC_RESULT
VAR_INPUT
	HWRITER : RTS_IEC_HANDLE;
	PNEWBUFFER : POINTER TO BYTE;
	DWNEWBUFFERSIZE : DWORD;
	PPOLDBUFFER : POINTER TO POINTER TO BYTE;
END_VAR
END_FUNCTION