FUNCTION SYSSOCKRECVFROMUDP : __XINT
VAR_INPUT
	HSOCKETUDP : RTS_IEC_HANDLE;
	PBYDATA : POINTER TO BYTE;
	DIDATASIZE : __XINT;
	PREPLY : POINTER TO UDP_REPLY;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION