FUNCTION SYSSOCKGETNEXTADAPTERINFO : RTS_IEC_HANDLE
VAR_INPUT
	HPREVADAPTER : RTS_IEC_HANDLE;
	PADAPTERINFO : POINTER TO SOCK_ADAPTER_INFORMATION;
	PUXIADAPTERINFOSIZE : POINTER TO __UXINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION