FUNCTION SYSSOCKSELECT : RTS_IEC_RESULT
VAR_INPUT
	DIWIDTH : DINT;
	PFDREAD : POINTER TO SOCKET_FD_SET;
	PFDWRITE : POINTER TO SOCKET_FD_SET;
	PFDEXCEPT : POINTER TO SOCKET_FD_SET;
	PTVTIMEOUT : POINTER TO SOCKET_TIMEVAL;
	PDIREADY : POINTER TO DINT;
END_VAR
END_FUNCTION