FUNCTION SYSSOCKACCEPT : RTS_IEC_HANDLE
VAR_INPUT
	HSOCKET : RTS_IEC_HANDLE;
	PSOCKADDR : POINTER TO SOCKADDRESS;
	PDISOCKADDRSIZE : POINTER TO DINT;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION