FUNCTION L_SEMP_GETACCESSACTSTATEDETERMINEPARAMETER : BOOL
VAR_INPUT
	PPARAMETER : POINTER TO BYTE;
	SEVERITY : POINTER TO USINT;
	EVENTID : POINTER TO WORD;
	TEXTREFID : POINTER TO WORD;
	ACTSTATEDETERMINEEVENT : POINTER TO DWORD;
END_VAR
END_FUNCTION