FUNCTION L_SEMP_GETACCESSACTSTATEDETERMINEPARAMETER3 : BOOL
VAR_INPUT
	PPARAMETER : POINTER TO BYTE;
	SEVERITY : POINTER TO USINT;
	EVENTID : POINTER TO WORD;
	TEXTREFID : POINTER TO WORD;
	ACTSTATEDETERMINEEVENT : POINTER TO DWORD;
	ACTERRORCODE : POINTER TO DWORD;
	USERGROUP : POINTER TO USINT;
END_VAR
END_FUNCTION