FUNCTION _GETALARMSFROMSTORAGE : BOOL
VAR_INPUT
	ISKIPROWS : INT;
	IMAXROWS : INT;
	PSTARRALARMGROUPS : POINTER TO ARRAY [0..0] OF UDINT;
	ICOUNTALARMGROUPS : INT;
	BALLALARMGROUPS : BOOL;
	PSTARRALARMCLASSES : POINTER TO ARRAY [0..0] OF UDINT;
	ICOUNTALARMCLASSES : INT;
	BALLALARMCLASSES : BOOL;
	USIPRIORITYFROM : USINT;
	USIPRIORITYTO : USINT;
	ALARMDATABLOCK : IAlarmDataBlockBase2;
END_VAR
VAR_IN_OUT
	BROWIDVALID : BOOL;
	DIROWID : DINT;
END_VAR
END_FUNCTION