FUNCTION ELABORATELATCHFILTERCRITERIA : BOOL
VAR_INPUT
	FILTERTYPE : EFilterLatchContent;
	FILTERVALUE : WSTRING;
END_VAR
VAR_OUTPUT
	FILTERTYPEELAB : EFilterLatchContent;
	WSVALUE : WSTRING;
	VTYPE : Visu_Types;
	LIVALUE : LINT;
	RVALUE : REAL;
	LRVALUE : LREAL;
END_VAR
END_FUNCTION