FUNCTION FORMATTIMESTAMP2 : BOOL
VAR_INPUT
	LITIMESTAMP : Timestamp;
	IOFFSET : INT;
	CBSRESULT : REFERENCE TO CharBufferString;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION