FUNCTION GETCOUNTALARMSFROMSTORAGE : DINT
VAR_INPUT
	FILTERCRITERIA : REFERENCE TO VisuFbAlarmFilterCriteria;
	ALARMDATABLOCK : IAlarmDataBlockBase2;
END_VAR
VAR_OUTPUT
	EERROR : STO.ERROR;
END_VAR
END_FUNCTION