FUNCTION REPLACEALARMMESSAGEPLACEHOLDERS2 : BOOL
VAR_INPUT
	RCBSTEXT : REFERENCE TO CharBufferString;
	RCBSBUFFER : REFERENCE TO CharBufferString;
	TIMESTAMP : SYSTIMEDATE;
	ESTATE : AlarmState;
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	ITFALARMMETAOBJECTSTUB3 : IAlarmMetaObjectStub3;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION