FUNCTION REPLACEALARMPLACEHOLDERS3 : BOOL
VAR_INPUT
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	RCBSRESULT : REFERENCE TO CharBufferString;
	TIMESTAMP : Timestamp;
	CBPMESSAGE : CharBufferPtr;
	ESTATE : AlarmState;
	SEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	SALARMID : STRING;
	ITFCURRENTVALUE : ITypedValue;
	ITFTRIGGERVALUE : ITypedValue;
	ITFLATCHVAR1VALUE : ITypedValue;
	ITFLATCHVAR2VALUE : ITypedValue;
	ITFHASMESSAGEPLACEHOLDER : IHasMessagePlaceholder;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION