FUNCTION REPLACEALARMFORMATTEDMSGPLACEHOLDER : BOOL
VAR_INPUT
	CBSINPUT : REFERENCE TO CharBufferString;
	CBSTOREPLACE : REFERENCE TO CharBufferString;
	ITFTYPEDVALUE : ITypedValue;
END_VAR
END_FUNCTION