FUNCTION L_IE1P_READERRORDATAFROMCOMPONENTLIST : BOOL
VAR_INPUT
	MODULEHANDLE : UDINT;
	PDATA : POINTER TO L_IE1P_ReadErrorData;
END_VAR
VAR_OUTPUT
	SEVERITY : L_IE1P_SeverityLevel;
	ERRORCODE : DWORD := 0;
END_VAR
VAR_IN_OUT
	DWCOMPIDX : DWORD;
END_VAR
END_FUNCTION