FUNCTION CODEMGETCONTENTBYFIRMCODE2 : RTS_IEC_RESULT
VAR_INPUT
	DUIFIRMCODE : UDINT;
	DUIPRODUCTCODE : UDINT;
	BRELEASELICENSE : BOOL;
END_VAR
VAR_IN_OUT
	LICENSEENTRY : RTS_CMBOXENTRY;
END_VAR
END_FUNCTION