FUNCTION ABC2R : BOOL
VAR_INPUT
	A_DEG : LREAL;
	B_DEG : LREAL;
	C_DEG : LREAL;
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
END_VAR
VAR_IN_OUT
	ROTMAT : ARRAY [1..3, 1..3] OF LREAL;
END_VAR
END_FUNCTION