FUNCTION ABC2QUAT : BOOL
VAR_INPUT
	A_DEG : LREAL;
	B_DEG : LREAL;
	C_DEG : LREAL;
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
END_VAR
VAR_IN_OUT
	QUAT : ARRAY [1..4] OF LREAL;
END_VAR
END_FUNCTION