FUNCTION ACCKART2ZYL : BOOL
VAR_IN_OUT
	ALRINPOSZYL : ARRAY [1..6] OF LREAL;
	ALRINACCKART : ARRAY [1..6] OF LREAL;
	ALRT_10 : ARRAY [1..4, 1..4] OF LREAL;
	ALROUT : ARRAY [1..6] OF LREAL;
END_VAR
END_FUNCTION