FUNCTION FINDINTERVAL : BOOL
VAR_INPUT
	LRVALUE : LREAL;
	PLRVALUES : POINTER TO LREAL;
	NDATA : UDINT;
	XZEROBASED : BOOL;
	XTRYFIRST : BOOL;
END_VAR
VAR_IN_OUT
	UDIINTERVAL : UDINT;
END_VAR
END_FUNCTION