FUNCTION QUAT2ABC : BOOL
VAR_INPUT
	EROTATIONCONVENTION : L_UMTP_RotationConvention;
	XCALCABC2 : BOOL := TRUE;
END_VAR
VAR_IN_OUT
	ABC : ARRAY [1..3] OF LREAL;
	ABC2 : ARRAY [1..3] OF LREAL;
	QUAT : ARRAY [1..4] OF LREAL;
END_VAR
END_FUNCTION