FUNCTION STRETCHPROFILETOTIME_RAST2RAST : BOOL
VAR_INPUT
	LRTDESIRED : LREAL;
	LRTASKCYCLE : LREAL;
END_VAR
VAR_IN_OUT
	SCPROFILEDATA : L_MC1P_ProfileData;
	SCPARAM : L_MC1P_ProfileParameter;
END_VAR
END_FUNCTION