/**
 * Write every fixture's EVIDENCE rating into `fixtures/evidence.generated.ts`.
 *
 *   bun run rate:fixtures          # regenerate
 *   bun run rate:fixtures --check  # report what would change, write nothing
 *
 * WHY A GENERATED MODULE AND NOT A FIELD IN EACH FIXTURE. About half the catalog is not literal objects: 458 of the
 * 963 fixtures come from factory helpers (`fb("cc_…", …)`) or carry template-literal names
 * (`` name: `cc_enum_into_${target}` ``). A per-entry field reaches only the literal half, which would leave the
 * annotation inconsistent — present on one fixture and absent on its neighbour for a reason that is about how the
 * file is written rather than about the evidence. One module keyed by name reaches all of them, and
 * `fixtures/index.ts` merges it so `t.evidence` is populated on EVERY fixture at runtime.
 *
 * It is derived data, so it is generated and then CHECKED: `fixtures.test.ts` recomputes every rating and fails if
 * a stored one disagrees. That is what makes it safe to commit — it can be read, diffed and reviewed, and it cannot
 * go stale without a red test.
 *
 * Re-run after `record:exec` or `record:language`, which is when a rating can legitimately change.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { ALL_TESTS } from "../test/conformance/fixtures/index.js"
import { EVIDENCE_ORDER, rateFixture, type Evidence } from "../test/conformance/support/evidence.js"

const OUT = join(import.meta.dir, "..", "test", "conformance", "fixtures", "evidence.generated.ts")
const check = process.argv.includes("--check")

const rated = ALL_TESTS.map((t) => [t.name, rateFixture(t, ALL_TESTS)] as const)
const tally = new Map<Evidence, number>()
for (const [, r] of rated) tally.set(r, (tally.get(r) ?? 0) + 1)

const lines = [...rated].sort((a, b) => a[0].localeCompare(b[0])).map(([name, r]) => `  ${name}: "${r}",`)

const header = `/**
 * GENERATED by \`bun run rate:fixtures\` — do not edit.
 *
 * How well each fixture is evidenced, keyed by name. \`fixtures/index.ts\` merges this onto every fixture, so
 * \`t.evidence\` is populated whether the fixture is a literal object or built by a factory; \`fixtures.test.ts\`
 * recomputes all of it and fails if anything here is stale. \`support/evidence.ts\` defines what each rating means.
 *
 * At the last regeneration:
${EVIDENCE_ORDER.filter((r) => (tally.get(r) ?? 0) > 0)
  .map((r) => ` *   ${r.padEnd(12)} ${String(tally.get(r)).padStart(4)}`)
  .join("\n")}
 */
import type { LanguageTest } from "../types.js"

export const FIXTURE_EVIDENCE: Readonly<Record<string, NonNullable<LanguageTest["evidence"]>>> = {
${lines.join("\n")}
}
`

const before = (() => {
  try {
    return readFileSync(OUT, "utf8")
  } catch {
    return ""
  }
})()

if (check) {
  if (before === header) {
    console.log(`evidence is current for ${rated.length} fixtures`)
    process.exit(0)
  }
  console.log("evidence.generated.ts is STALE — run `bun run rate:fixtures`")
  process.exit(1)
}

writeFileSync(OUT, header)
console.log(`rated ${rated.length} fixtures -> ${OUT}`)
for (const r of EVIDENCE_ORDER) if ((tally.get(r) ?? 0) > 0) console.log(`  ${r.padEnd(12)} ${tally.get(r)}`)
