/**
 * Conformance recorder — re-creates `test/conformance/recordings/expected-<vendor>.json` from a LIVE bridge.
 * (The original was removed with volt-agent; this is the self-contained replacement built on the raw wire.)
 *
 *   VOLT_BRIDGE_PORT=8556 VOLT_VENDOR=codesys bun run scripts/record-language.ts        # CODESYS
 *   VOLT_BRIDGE_PORT=8555 VOLT_VENDOR=tc       bun run scripts/record-language.ts        # TwinCAT
 *
 * Each fixture is recorded ISOLATED (push → instantiate in PLC_PRG → build → capture → restore), so no
 * cross-fixture batch short-circuit can drop diagnostics. Writes to `expected-<vendor>.new.json` by default
 * (non-destructive); pass `--write` to overwrite the trusted recording. Only error+warning severities are
 * kept (info/"Compile complete" dropped), matching the committed format the replay consumes.
 */
import { writeFileSync } from "node:fs"
import { join } from "node:path"
import { ALL_TESTS } from "../test/conformance/fixtures/index.js"

const PORT = process.env.VOLT_BRIDGE_PORT ?? "8556"
const VENDOR = process.env.VOLT_VENDOR ?? "codesys"
const WRITE = process.argv.includes("--write")
const BASE = `http://127.0.0.1:${PORT}`
const EXT: Record<string, string> = { function_block: "fb", function: "fun", program: "prg", gvl: "gvl", structure: "struct", interface: "itf" }

const get = async (p: string): Promise<any> => (await fetch(BASE + p)).json()
const post = async (p: string, body: unknown): Promise<any> =>
  (await fetch(BASE + p, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) })).json()

async function pushOps(ops: unknown[]): Promise<void> {
  const r = await post("/push", { expectedProjectVersion: (await get("/refs")).projectVersion, ops })
  if (!r.accepted) console.warn("  push rejected:", JSON.stringify(r.conflicts ?? r).slice(0, 160))
}
async function fetchItem(name: string): Promise<any> {
  const f = await post("/fetch", { knownItems: {}, onlyItems: [name] })
  return (f.changed ?? []).find((i: any) => i.name === name)
}
const version = async (name: string): Promise<string | null> => (await get("/refs")).items[name] ?? null

// Resolve PLC_PRG (CODESYS) / MAIN (TwinCAT) + its folder; save the original body for restore.
const refs0 = await get("/refs")
const plcName = ["PLC_PRG.prg", "MAIN.prg"].find((n) => refs0.items[n])
if (plcName === undefined) throw new Error("no PLC_PRG/MAIN in project")
const plcItem0 = await fetchItem(plcName)
const plcFolder = plcItem0.folder ?? ""
const plcOriginal: string = plcItem0.sourceText

async function setPlcPrg(src: string): Promise<void> {
  await pushOps([{ op: "set", name: plcName, toFolder: "", sourceText: src, ifVersion: await version(plcName) }])
}

const tests: Record<string, { buildSuccess: boolean; durationMs: number; diagnostics: { severity: string; message: string; line: number }[] }> = {}
let done = 0
for (const t of ALL_TESTS) {
  if (t.recorderSkip) continue
  const wire = `${t.pouName}.${EXT[t.kind] ?? "fb"}`
  try {
    await pushOps([{ op: "set", name: wire, toFolder: plcFolder, sourceText: t.source, ifVersion: null }])
    if (t.plcPrgVar !== undefined || t.plcPrgBody !== undefined) {
      await setPlcPrg(`PROGRAM PLC_PRG\nVAR\n${t.plcPrgVar ?? ""}\nEND_VAR\n${t.plcPrgBody ?? ""}\nEND_PROGRAM\n`)
    }
    const started = performance.now()
    const r = await post("/build", { buildType: "incremental" })
    const durationMs = Math.round(performance.now() - started)
    const diagnostics = (r.diagnostics ?? [])
      .filter((d: any) => d.severity === "error" || d.severity === "warning")
      .map((d: any) => ({ severity: d.severity, message: d.message, line: d.line ?? 0 }))
    tests[t.name] = { buildSuccess: !!r.success, durationMs, diagnostics }
  } catch (e) {
    console.warn(`  ${t.name}: ERROR ${(e as Error).message}`)
  } finally {
    // restore: delete the fixture, put PLC_PRG back
    await pushOps([{ op: "deleteItem", name: wire, ifVersion: await version(wire) }])
    if (plcOriginal !== undefined) await setPlcPrg(plcOriginal)
  }
  if (++done % 25 === 0) console.log(`  …${done} recorded`)
}

const out = {
  $schema: `./expected-${VENDOR === "tc" ? "tc" : VENDOR}.schema.json`,
  _doc: "Auto-generated by scripts/record-language.ts. Do not edit by hand — re-record after editing the catalog.",
  recorded: { at: new Date().toISOString(), bridgeVersion: (await get("/health")).version ?? "1.0.0", testCount: Object.keys(tests).length },
  tests,
}
const file = `expected-${VENDOR === "tc" ? "tc" : VENDOR}.${WRITE ? "" : "new."}json`
const path = join(import.meta.dir, "..", "test", "conformance", "recordings", file)
writeFileSync(path, JSON.stringify(out, null, 2) + "\n")
console.log(`\nWrote ${Object.keys(tests).length} tests → ${path}`)
