/**
 * Corpus build recorder — captures the REAL IDE build diagnostics of a corpus project into a checked-in
 * snapshot, so `build-conformance.test.ts` can hold every LSP error to "the compiler actually emitted this".
 * This is the ground truth the `corpus.test.ts` zero-FP gate lacked (it assumed the projects compile clean;
 * they do NOT — see the C0371 demotion). Run it ONCE per project, with that project loaded in the live IDE:
 *
 *   1. Open the project in CODESYS (or TwinCAT) so the bridge serves it.
 *   2. Bring the bridge up (pwsh packages/volt-cli/scripts/codesys-pipe.ps1 up -Project <path>), or point at your running IDE's bridge.
 *   3. PROJECT=lenze-mid VOLT_VENDOR=codesys bun run scripts/record-corpus-build.ts
 *
 * Writes test-corpus/<PROJECT>/expected-build.<vendor>.json = every error+warning the FULL build emitted.
 * The comparison is project-level (message set), matching replay.test.ts — so our wording must match the IDE's
 * for a real detection to count (a wording delta reads as an FP until reconciled, which is the point).
 */
import { writeFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { get, post, TARGET } from "./bridge.js"

const PROJECT = process.env.PROJECT
if (PROJECT === undefined) throw new Error("set PROJECT=<corpus folder name> (e.g. lenze-mid)")
const dir = join(import.meta.dir, "..", "test-corpus", PROJECT)
if (!existsSync(dir)) throw new Error(`no corpus project at ${dir}`)

const health = await get("/health")
const vendor = process.env.VOLT_VENDOR ?? (health.platform === "twincat" ? "tc" : "codesys")

console.log(`Building ${PROJECT} on ${TARGET} (${vendor}) …`)
const r = await post("/build", { buildType: "full" })
const diagnostics = (r.diagnostics ?? [])
  .filter((d: any) => d.severity === "error" || d.severity === "warning")
  .map((d: any) => ({ severity: d.severity, message: String(d.message), line: d.line ?? 0 }))

const out = {
  _doc: "Real IDE build diagnostics for this corpus project. Auto-generated by scripts/record-corpus-build.ts — re-record after a project change. Consumed by test/corpus/build-conformance.test.ts.",
  recorded: { at: new Date().toISOString(), vendor, buildSuccess: !!r.success, count: diagnostics.length },
  diagnostics,
}
const path = join(dir, `expected-build.${vendor}.json`)
writeFileSync(path, JSON.stringify(out, null, 2) + "\n")
console.log(`Wrote ${diagnostics.length} diagnostics → ${path}`)
