/**
 * Differential-execution recorder — re-creates `test/exec/recordings/expected-codesys.json` from CODESYS itself.
 *
 *   bun run record:exec          # Windows + CODESYS 3.5.21.40 (SP21); ~5s per case after a ~1min launch
 *
 * Launches a headless CODESYS with `record-exec.py` as its runscript, which opens a COPY of the committed fixture,
 * puts its device in simulation, and runs every case in `test/exec/cases.ts` there (see the .py for the three
 * measured facts that shape it). Not a bridge op: the scripting online object only works inside a running script.
 *
 * Variable names come from the PARSER, not from lowering, so a case the interpreter cannot run yet (a built-in,
 * say) is still recorded — the ground truth is wanted BEFORE the implementation, not after.
 */
import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { parseSource } from "../src/syntax/index.js"
import { CASES, programSource } from "../test/exec/cases.js"

const CODESYS = "C:\\Program Files\\CODESYS 3.5.21.40\\CODESYS\\Common\\CODESYS.exe"
const PROFILE = "CODESYS V3.5 SP21 Patch 4"
const PROJECT =
  process.env.VOLT_EXEC_PROJECT ?? join(import.meta.dir, "..", "..", "volt-cli", "test", "fixtures", "CodesysTestProject.project")

const cases = CASES.map((c) => {
  const unit = parseSource(programSource(c)).units[0] as { varSections?: { decls: { names: { text: string }[] }[] }[] }
  const names = (unit.varSections ?? []).flatMap((s) => s.decls.flatMap((d) => d.names.map((n) => n.text)))
  if (names.length === 0) throw new Error(`${c.name}: no variables parsed — nothing to compare`)
  return { name: c.name, vars: c.vars, body: c.body, cycles: c.cycles ?? 1, names }
})

const work = join(tmpdir(), "volt-exec-oracle")
mkdirSync(work, { recursive: true })
const casesPath = join(work, "cases.json")
const outPath = join(work, "result.json")
rmSync(outPath, { force: true })
// Non-ASCII as JSON `\uXXXX` escapes: the runscript's IronPython `json` reads raw UTF-8 as one character per BYTE, so
// "héllo" reached CODESYS as "hÃ©llo" — which is why a WSTRING(3) of it recorded as "hé" (three units, not two).
const asciiJson = (text: string): string =>
  text.replace(/[^\x00-\x7f]/g, (ch) => "\\u" + ch.charCodeAt(0).toString(16).padStart(4, "0"))
writeFileSync(casesPath, asciiJson(JSON.stringify(cases)))

console.log(`recording ${cases.length} case(s) in CODESYS simulation (log: ${outPath}.log)…`)
// Verbatim arguments: CODESYS parses `--profile="…"` itself, and Node's own quoting would wrap the WHOLE argument.
spawnSync(CODESYS, [`--profile="${PROFILE}"`, "--noUI", `--runscript="${join(import.meta.dir, "record-exec.py")}"`], {
  env: { ...process.env, VOLT_EXEC_CASES: casesPath, VOLT_EXEC_OUT: outPath, VOLT_EXEC_PROJECT: PROJECT },
  windowsVerbatimArguments: true,
  stdio: "ignore",
  timeout: 15 * 60_000, // a hang guard, not a budget: a healthy run is a few minutes
})
if (!existsSync(outPath)) throw new Error(`CODESYS wrote no recording — see ${outPath}.log`)

// The runscript writes each non-ASCII character as the TEXT `\uXXXX` (see `ascii_escaped` in the .py), which json.dump
// escapes once more; un-doubling the backslash makes it a real JSON escape again.
const result = JSON.parse(readFileSync(outPath, "utf8").replace(/\\\\u([0-9a-f]{4})/g, "\\u$1"))
const dir = join(import.meta.dir, "..", "test", "exec", "recordings")
mkdirSync(dir, { recursive: true })
writeFileSync(
  join(dir, "expected-codesys.json"),
  JSON.stringify({ _doc: "Generated by scripts/record-exec.ts. Do not edit by hand — re-record.", ...result }, null, 2) + "\n",
)
const failed = Object.entries(result.tests as Record<string, { error?: string }>).filter(([, t]) => t.error)
console.log(`recorded ${Object.keys(result.tests).length} case(s), ${failed.length} failed in the IDE`)
for (const [name, t] of failed) console.log(`  ${name}: ${t.error}`)
