PROGRAM MACH_ParameterHandler
VAR
	{warning 'Disabled for compatibility SVE'}
	//DiffLogger								: DifferenceLogger;
	CPY_HMI_sRecipeName  					: STRING;
    CPY_HMI_nDefaultLanguage 				: INT;
    CPY_HMI_nSecondLanguage  				: INT;
    CPY_HMI_dwMachineConfig  				: DWORD;
    CPY_HMI_dwProductOptions 				: DWORD;
    CPY_bAxis_RSet           				: BOOL;
    CPY_bAxis_FrontSet       				: BOOL;
    CPY_bAxis_RearSet        				: BOOL;
END_VAR

IF NOT g_sMCHCopyMade THEN
	CPY_HMI_sRecipeName      := g_HMI_sRecipeName     ;
    CPY_HMI_nDefaultLanguage := g_HMI_nDefaultLanguage;
    CPY_HMI_nSecondLanguage  := g_HMI_nSecondLanguage ;
    CPY_HMI_dwMachineConfig  := g_HMI_dwMachineConfig ;
    CPY_HMI_dwProductOptions := g_HMI_dwProductOptions;
    CPY_bAxis_RSet           := g_bAxis_RSet          ;
    CPY_bAxis_FrontSet       := g_bAxis_FrontSet      ;
    CPY_bAxis_RearSet        := g_bAxis_RearSet       ;

	g_sMCHParCopy := g_HMI_MCH_Parameters;
	g_sMCHCopyMade	:= TRUE;
END_IF

{warning 'Disabled for compatibility SVE'}
(*
DiffLogger.orig := __VARINFO(g_HMI_sRecipeName ); DiffLogger.copy := __VARINFO(          					  CPY_HMI_sRecipeName ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(          					  CPY_HMI_sRecipeName ), origStr := TO_STRING(g_HMI_sRecipeName ));
DiffLogger.orig := __VARINFO(g_HMI_nDefaultLanguage); DiffLogger.copy := __VARINFO(      					  CPY_HMI_nDefaultLanguage); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      					  CPY_HMI_nDefaultLanguage), origStr := TO_STRING(g_HMI_nDefaultLanguage));
DiffLogger.orig := __VARINFO(g_HMI_nSecondLanguage ); DiffLogger.copy := __VARINFO(      					  CPY_HMI_nSecondLanguage ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      					  CPY_HMI_nSecondLanguage ), origStr := TO_STRING(g_HMI_nSecondLanguage ));
DiffLogger.orig := __VARINFO(g_HMI_dwMachineConfig ); DiffLogger.copy := __VARINFO(      					  CPY_HMI_dwMachineConfig ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      					  CPY_HMI_dwMachineConfig ), origStr := TO_STRING(g_HMI_dwMachineConfig ));
DiffLogger.orig := __VARINFO(g_HMI_dwProductOptions); DiffLogger.copy := __VARINFO(      					  CPY_HMI_dwProductOptions); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      					  CPY_HMI_dwProductOptions), origStr := TO_STRING(g_HMI_dwProductOptions));
DiffLogger.orig := __VARINFO(g_bAxis_RSet ); DiffLogger.copy := __VARINFO(               					  CPY_bAxis_RSet ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(               					  CPY_bAxis_RSet ), origStr := TO_STRING(g_bAxis_RSet ));
DiffLogger.orig := __VARINFO(g_bAxis_FrontSet ); DiffLogger.copy := __VARINFO(           					  CPY_bAxis_FrontSet ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(           					  CPY_bAxis_FrontSet ), origStr := TO_STRING(g_bAxis_FrontSet ));
DiffLogger.orig := __VARINFO(g_bAxis_RearSet ); DiffLogger.copy := __VARINFO(            					  CPY_bAxis_RearSet ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(            					  CPY_bAxis_RearSet ), origStr := TO_STRING(g_bAxis_RearSet ));
//DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rSizeOfKnife); DiffLogger.copy := __VARINFO(               g_sMCHParCopy.rSizeOfKnife); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(               g_sMCHParCopy.rSizeOfKnife), origStr := TO_STRING(g_HMI_MCH_Parameters.rSizeOfKnife));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rTimeOutAirvalve); DiffLogger.copy := __VARINFO(           g_sMCHParCopy.rTimeOutAirvalve); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(           g_sMCHParCopy.rTimeOutAirvalve), origStr := TO_STRING(g_HMI_MCH_Parameters.rTimeOutAirvalve));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rTimeSwitchOffAirvalve); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rTimeSwitchOffAirvalve); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rTimeSwitchOffAirvalve), origStr := TO_STRING(g_HMI_MCH_Parameters.rTimeSwitchOffAirvalve));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rKnifeRotationTimeout); DiffLogger.copy := __VARINFO(      g_sMCHParCopy.rKnifeRotationTimeout); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      g_sMCHParCopy.rKnifeRotationTimeout), origStr := TO_STRING(g_HMI_MCH_Parameters.rKnifeRotationTimeout));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumRotationTime); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMinimumRotationTime); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMinimumRotationTime), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumRotationTime));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdHeightTrayMinimum); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rProdHeightTrayMinimum); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rProdHeightTrayMinimum), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdHeightTrayMinimum));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayLarge_InX); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rProdLengthTrayLarge_InX); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rProdLengthTrayLarge_InX), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayLarge_InX));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayLarge_InY); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rProdLengthTrayLarge_InY); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rProdLengthTrayLarge_InY), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayLarge_InY));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTraySmall_InX); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rProdLengthTraySmall_InX); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rProdLengthTraySmall_InX), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTraySmall_InX));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTraySmall_InY); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rProdLengthTraySmall_InY); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rProdLengthTraySmall_InY), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTraySmall_InY));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayDouble_InX); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthTrayDouble_InX); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthTrayDouble_InX), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayDouble_InX));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayDouble_InY); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthTrayDouble_InY); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthTrayDouble_InY), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayDouble_InY));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayTriple_InX); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthTrayTriple_InX); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthTrayTriple_InX), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayTriple_InX));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthTrayTriple_InY); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthTrayTriple_InY); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthTrayTriple_InY), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthTrayTriple_InY));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthSlabDouble_InX); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthSlabDouble_InX); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthSlabDouble_InX), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthSlabDouble_InX));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rProdLengthSlabDouble_InY); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rProdLengthSlabDouble_InY); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rProdLengthSlabDouble_InY), origStr := TO_STRING(g_HMI_MCH_Parameters.rProdLengthSlabDouble_InY));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayLarge_X); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rStartPointTrayLarge_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rStartPointTrayLarge_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayLarge_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayLarge_Y); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rStartPointTrayLarge_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rStartPointTrayLarge_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayLarge_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTraySmall_X); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rStartPointTraySmall_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rStartPointTraySmall_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTraySmall_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTraySmall1_Y); DiffLogger.copy := __VARINFO(    g_sMCHParCopy.rStartPointTraySmall1_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(    g_sMCHParCopy.rStartPointTraySmall1_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTraySmall1_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTraySmall2_Y); DiffLogger.copy := __VARINFO(    g_sMCHParCopy.rStartPointTraySmall2_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(    g_sMCHParCopy.rStartPointTraySmall2_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTraySmall2_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayDouble1_X); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayDouble1_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayDouble1_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayDouble1_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayDouble2_X); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayDouble2_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayDouble2_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayDouble2_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayDouble_Y); DiffLogger.copy := __VARINFO(    g_sMCHParCopy.rStartPointTrayDouble_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(    g_sMCHParCopy.rStartPointTrayDouble_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayDouble_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointSlab_X); DiffLogger.copy := __VARINFO(          g_sMCHParCopy.rStartPointSlab_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(          g_sMCHParCopy.rStartPointSlab_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointSlab_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointSlab_Y); DiffLogger.copy := __VARINFO(          g_sMCHParCopy.rStartPointSlab_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(          g_sMCHParCopy.rStartPointSlab_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointSlab_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayTriple_X); DiffLogger.copy := __VARINFO(    g_sMCHParCopy.rStartPointTrayTriple_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(    g_sMCHParCopy.rStartPointTrayTriple_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayTriple_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayTriple1_Y); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayTriple1_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayTriple1_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayTriple1_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayTriple2_Y); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayTriple2_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayTriple2_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayTriple2_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayTriple3_Y); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayTriple3_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayTriple3_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayTriple3_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointTrayTriple4_Y); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointTrayTriple4_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointTrayTriple4_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointTrayTriple4_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointSlabDouble1_X); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointSlabDouble1_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointSlabDouble1_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointSlabDouble1_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointSlabDouble2_X); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rStartPointSlabDouble2_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rStartPointSlabDouble2_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointSlabDouble2_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rStartPointSlabDouble_Y); DiffLogger.copy := __VARINFO(    g_sMCHParCopy.rStartPointSlabDouble_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(    g_sMCHParCopy.rStartPointSlabDouble_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rStartPointSlabDouble_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake1_X); DiffLogger.copy := __VARINFO(        g_sMCHParCopy.rMidPosRoundCake1_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(        g_sMCHParCopy.rMidPosRoundCake1_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake1_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake1_Y); DiffLogger.copy := __VARINFO(        g_sMCHParCopy.rMidPosRoundCake1_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(        g_sMCHParCopy.rMidPosRoundCake1_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake1_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake2_X); DiffLogger.copy := __VARINFO(        g_sMCHParCopy.rMidPosRoundCake2_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(        g_sMCHParCopy.rMidPosRoundCake2_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake2_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake2_Y); DiffLogger.copy := __VARINFO(        g_sMCHParCopy.rMidPosRoundCake2_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(        g_sMCHParCopy.rMidPosRoundCake2_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake2_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake13_X); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMidPosRoundCake13_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMidPosRoundCake13_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake13_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake24_X); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMidPosRoundCake24_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMidPosRoundCake24_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake24_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake12_Y); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMidPosRoundCake12_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMidPosRoundCake12_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake12_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMidPosRoundCake34_Y); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMidPosRoundCake34_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMidPosRoundCake34_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rMidPosRoundCake34_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rInfeedPosition_X); DiffLogger.copy := __VARINFO(          g_sMCHParCopy.rInfeedPosition_X); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(          g_sMCHParCopy.rInfeedPosition_X), origStr := TO_STRING(g_HMI_MCH_Parameters.rInfeedPosition_X));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rInfeedPosition_Y); DiffLogger.copy := __VARINFO(          g_sMCHParCopy.rInfeedPosition_Y); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(          g_sMCHParCopy.rInfeedPosition_Y), origStr := TO_STRING(g_HMI_MCH_Parameters.rInfeedPosition_Y));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rManualSpeed); DiffLogger.copy := __VARINFO(               g_sMCHParCopy.rManualSpeed); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(               g_sMCHParCopy.rManualSpeed), origStr := TO_STRING(g_HMI_MCH_Parameters.rManualSpeed));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayLarge); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rMinimumTrimSizeTrayLarge); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rMinimumTrimSizeTrayLarge), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayLarge));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumTrimSizeTraySmall); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.rMinimumTrimSizeTraySmall); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.rMinimumTrimSizeTraySmall), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumTrimSizeTraySmall));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayDouble); DiffLogger.copy := __VARINFO( g_sMCHParCopy.rMinimumTrimSizeTrayDouble); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING( g_sMCHParCopy.rMinimumTrimSizeTrayDouble), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayDouble));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayTriple); DiffLogger.copy := __VARINFO( g_sMCHParCopy.rMinimumTrimSizeTrayTriple); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING( g_sMCHParCopy.rMinimumTrimSizeTrayTriple), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumTrimSizeTrayTriple));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rMinimumTrimSizeSlab); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rMinimumTrimSizeSlab); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rMinimumTrimSizeSlab), origStr := TO_STRING(g_HMI_MCH_Parameters.rMinimumTrimSizeSlab));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.dnMaintenanceInterval); DiffLogger.copy := __VARINFO(      g_sMCHParCopy.dnMaintenanceInterval); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      g_sMCHParCopy.dnMaintenanceInterval), origStr := TO_STRING(g_HMI_MCH_Parameters.dnMaintenanceInterval));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.bUltrasonicEnable1); DiffLogger.copy := __VARINFO(         g_sMCHParCopy.bUltrasonicEnable1); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(         g_sMCHParCopy.bUltrasonicEnable1), origStr := TO_STRING(g_HMI_MCH_Parameters.bUltrasonicEnable1));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.bSkipImpossiblePositions ); DiffLogger.copy := __VARINFO(  g_sMCHParCopy.bSkipImpossiblePositions ); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(  g_sMCHParCopy.bSkipImpossiblePositions ), origStr := TO_STRING(g_HMI_MCH_Parameters.bSkipImpossiblePositions ));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosTrayLarge); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rBottomZPosTrayLarge); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rBottomZPosTrayLarge), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosTrayLarge));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosTraySmall); DiffLogger.copy := __VARINFO(       g_sMCHParCopy.rBottomZPosTraySmall); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(       g_sMCHParCopy.rBottomZPosTraySmall), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosTraySmall));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosTrayDouble); DiffLogger.copy := __VARINFO(      g_sMCHParCopy.rBottomZPosTrayDouble); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      g_sMCHParCopy.rBottomZPosTrayDouble), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosTrayDouble));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosTrayTriple); DiffLogger.copy := __VARINFO(      g_sMCHParCopy.rBottomZPosTrayTriple); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      g_sMCHParCopy.rBottomZPosTrayTriple), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosTrayTriple));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosSlab); DiffLogger.copy := __VARINFO(            g_sMCHParCopy.rBottomZPosSlab); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(            g_sMCHParCopy.rBottomZPosSlab), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosSlab));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosRound); DiffLogger.copy := __VARINFO(           g_sMCHParCopy.rBottomZPosRound); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(           g_sMCHParCopy.rBottomZPosRound), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosRound));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosRoundQuatro); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rBottomZPosRoundQuatro); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rBottomZPosRoundQuatro), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosRoundQuatro));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rBottomZPosSlabDouble); DiffLogger.copy := __VARINFO(      g_sMCHParCopy.rBottomZPosSlabDouble); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(      g_sMCHParCopy.rBottomZPosSlabDouble), origStr := TO_STRING(g_HMI_MCH_Parameters.rBottomZPosSlabDouble));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rPushBarSize); DiffLogger.copy := __VARINFO(               g_sMCHParCopy.rPushBarSize); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(               g_sMCHParCopy.rPushBarSize), origStr := TO_STRING(g_HMI_MCH_Parameters.rPushBarSize));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanXPosStart); DiffLogger.copy := __VARINFO(            g_sMCHParCopy.rCleanXPosStart); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(            g_sMCHParCopy.rCleanXPosStart), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanXPosStart));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanYPosStart); DiffLogger.copy := __VARINFO(            g_sMCHParCopy.rCleanYPosStart); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(            g_sMCHParCopy.rCleanYPosStart), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanYPosStart));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanYPosStop); DiffLogger.copy := __VARINFO(             g_sMCHParCopy.rCleanYPosStop); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(             g_sMCHParCopy.rCleanYPosStop), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanYPosStop));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanZPosFlap); DiffLogger.copy := __VARINFO(             g_sMCHParCopy.rCleanZPosFlap); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(             g_sMCHParCopy.rCleanZPosFlap), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanZPosFlap));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanZPosWaterContainer); DiffLogger.copy := __VARINFO(   g_sMCHParCopy.rCleanZPosWaterContainer); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(   g_sMCHParCopy.rCleanZPosWaterContainer), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanZPosWaterContainer));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleanContainerTimeOut); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.rCleanContainerTimeOut); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.rCleanContainerTimeOut), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleanContainerTimeOut));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rCleaningSpeed); DiffLogger.copy := __VARINFO(             g_sMCHParCopy.rCleaningSpeed); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(             g_sMCHParCopy.rCleaningSpeed), origStr := TO_STRING(g_HMI_MCH_Parameters.rCleaningSpeed));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.sFTPMachineDesignation); DiffLogger.copy := __VARINFO(     g_sMCHParCopy.sFTPMachineDesignation); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(     g_sMCHParCopy.sFTPMachineDesignation), origStr := TO_STRING(g_HMI_MCH_Parameters.sFTPMachineDesignation));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.sFTPAdress); DiffLogger.copy := __VARINFO(                 g_sMCHParCopy.sFTPAdress); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(                 g_sMCHParCopy.sFTPAdress), origStr := TO_STRING(g_HMI_MCH_Parameters.sFTPAdress));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.sFTPUser); DiffLogger.copy := __VARINFO(                   g_sMCHParCopy.sFTPUser); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(                   g_sMCHParCopy.sFTPUser), origStr := TO_STRING(g_HMI_MCH_Parameters.sFTPUser));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.sFTPPassword); DiffLogger.copy := __VARINFO(               g_sMCHParCopy.sFTPPassword); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(               g_sMCHParCopy.sFTPPassword), origStr := TO_STRING(g_HMI_MCH_Parameters.sFTPPassword));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.dFTPPort); DiffLogger.copy := __VARINFO(                   g_sMCHParCopy.dFTPPort); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(                   g_sMCHParCopy.dFTPPort), origStr := TO_STRING(g_HMI_MCH_Parameters.dFTPPort));
DiffLogger.orig := __VARINFO(g_HMI_MCH_Parameters.rSpeedZ_CrashDetect); DiffLogger.copy := __VARINFO(        g_sMCHParCopy.rSpeedZ_CrashDetect); DiffLogger(	Logger := ADR(g_Logger), copyStr := TO_STRING(        g_sMCHParCopy.rSpeedZ_CrashDetect), origStr := TO_STRING(g_HMI_MCH_Parameters.rSpeedZ_CrashDetect));
*)

END_PROGRAM
