FUNCTION _CREATEARRAYRECEIVER : CAA.HANDLE
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	PASORTEDCOBIDS : POINTER TO CL2I.ARRAY_RECV_ENTRY;
	CTCOBIDS : CAA.COUNT;
	EEVENT : CB.EVENT;
	XENABLESYNCWINDOW : BOOL;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION