FUNCTION _CREATEMASKRECEIVER : CAA.HANDLE
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	COBIDVALUE : CL2I.COBID;
	COBIDMASK : CL2I.COBID;
	XRTRVALUE : BOOL;
	XRTRMASK : BOOL;
	X29BITIDVALUE : BOOL;
	X29BITIDMASK : BOOL;
	XTRANSMITVALUE : BOOL;
	XTRANSMITMASK : BOOL;
	XALWAYSNEWEST : BOOL;
	EEVENT : CB.EVENT;
	XENABLESYNCWINDOW : BOOL;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION