FUNCTION _CREATESINGLEIDRECEIVER : CAA.HANDLE
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	COBID : CL2I.COBID;
	XRTR : BOOL;
	X29BITID : BOOL;
	XTRANSMIT : BOOL;
	XALWAYSNEWEST : BOOL;
	EEVENT : CB.EVENT;
	XENABLESYNCWINDOW : BOOL;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION