FUNCTION _ENABLESYNCSERVICE : ERROR
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	COBID : CL2I.COBID;
	XSYNCPRODUCER : BOOL;
	XENABLESYNCEVENT : BOOL;
	UDISYNCCYCLE : UDINT;
	UDISYNCWINDOWLENGTH : UDINT;
	UDISYNCFOREWARNTIME : UDINT;
END_VAR
END_FUNCTION