FUNCTION _REGISTERIDAREA : ERROR
VAR_INPUT
	HRECEIVERID : CAA.HANDLE;
	COBIDSTART : CL2I.COBID;
	COBIDEND : CL2I.COBID;
	XRTRVALUE : BOOL;
	XRTRMASK : BOOL;
	X29BITIDVALUE : BOOL;
	X29BITIDMASK : BOOL;
	XTRANSMITVALUE : BOOL;
	XTRANSMITMASK : BOOL;
END_VAR
END_FUNCTION