FUNCTION CREATEIDAREARECEIVEREX : CAA.HANDLE
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	XALWAYSNEWEST : BOOL;
	XREVERSE : BOOL;
	EEVENT : CB.EVENT;
	XENABLESYNCWINDOW : BOOL;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION