FUNCTION CSTCYCLEOPEN : CAA.HANDLE
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	ECSTEVENT : CB.EVENT;
	USIPRIORITY : USINT;
	XENABLESYNCWINDOW : BOOL;
	UDICSTCYCLE : UDINT;
	UDICSTFOREWARNTIME : UDINT;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION