FUNCTION DRIVEROPENP : CAA.HANDLE
VAR_INPUT
	USINETID : USINT;
	UIBAUDRATE : UINT;
	XSUPPORT29BITS : BOOL;
	SZMEMSIZE : CAA.SIZE;
	PMEMORY : CAA.PVOID;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION