FUNCTION ENABLETIMESERVICE : ERROR
VAR_INPUT
	HDRIVER : CAA.HANDLE;
	COBID : CL2I.COBID;
	XTIMEPRODUCER : BOOL;
	XENABLETIMEEVENT : BOOL;
	UDITIMECYCLE : UDINT;
	UDITIMEFOREWARNTIME : UDINT;
END_VAR
END_FUNCTION