FUNCTION ANALYZEPLACEHOLDERSINTERNAL : PlaceholderAnalyzationState
VAR_INPUT
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	PAPLACEHOLDERS : POINTER TO ARRAY [0..0] OF PlaceholderDescription;
	ICOUNTPLACEHOLDERTOCHECK : INT;
	PAPLACEHOLDEROCCURRENCE : POINTER TO ARRAY [0..0] OF PlaceholderOccurrence;
	SIMAXCOUNTPLACEHOLDERS : SINT;
END_VAR
VAR_OUTPUT
	SICOUNTPLACEHOLDERS : SINT;
END_VAR
END_FUNCTION