FUNCTION GETALARMMESSAGEFROMPROXY : BOOL
VAR_INPUT
	ITFALARMMETAOBJECTSTUB5 : IAlarmMetaObjectStub5;
	IWHICHMESSAGE : INT;
	REFCHARBUFFERSTRING : REFERENCE TO CharBufferString;
	STRINGTYPE : __SYSTEM.TYPE_CLASS;
END_VAR
END_FUNCTION