FUNCTION GETACTIVEALARMSFROMPROXY : BOOL
VAR_INPUT
	PASNAME : POINTER TO ARRAY [0..10] OF STRING;
	IGROUPCOUNT : INT;
	FILTERCRITERIA : REFERENCE TO VisuFbAlarmFilterCriteria;
	ITFALARMDATABLOCK : IAlarmDataBlockBaseDINT;
END_VAR
VAR_IN_OUT
	DISTUBPROG : DINT;
END_VAR
END_FUNCTION