FUNCTION REPLACEALARMPLACEHOLDERS4BASE : BOOL
VAR_INPUT
	IWHICHMESSAGE : INT;
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	RCBSRESULT : REFERENCE TO CharBufferString;
	CBPMESSAGE : CharBufferPtr;
	ESTATE : AlarmState;
	SEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	SALARMID : STRING;
	ITFHASMESSAGEPLACEHOLDER : IHasMessagePlaceholder;
	IFTALARMADDITIONALLATCHVARIABLES : IAlarmAdditionalLatchVariables;
	TIMESTAMP : Timestamp;
	IOFFSET : INT;
	ITFCURRENTVALUE : ITypedValue;
	ITFTRIGGERVALUE : ITypedValue;
	ITFLATCHVAR1 : ITypedValue;
	ITFLATCHVAR2 : ITypedValue;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION