FUNCTION REPLACEALARMPLACEHOLDERS4 : BOOL
VAR_INPUT
	IWHICHMESSAGE : INT;
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	RCBSRESULT : REFERENCE TO CharBufferString;
	ITFALARMMETAOBJECTSTUB3 : IAlarmMetaObjectStub3;
	CBPMESSAGE : CharBufferPtr;
	ESTATE : AlarmState;
	SEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	SALARMID : STRING;
	ITFHASMESSAGEPLACEHOLDER : IHasMessagePlaceholder;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION