FUNCTION REPLACEALARMPLACEHOLDERS2FALLBACK : BOOL
VAR_INPUT
	CBSMESSAGE : REFERENCE TO CharBufferString;
	CBSRESULT : REFERENCE TO CharBufferString;
	ITFALARM : IAlarm;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION