FUNCTION REPLACEALARMPLACEHOLDERS : BOOL
VAR_INPUT
	CBSMESSAGE : REFERENCE TO CharBufferString;
	CBSRESULT : REFERENCE TO CharBufferString;
	TIMESTAMP : Timestamp;
	CBPMESSAGE : CharBufferPtr;
	STATE : AlarmState;
	STEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	STALARMCLASSNAME : STRING;
	STALARMID : STRING;
	CURRENTVALUE : ITypedValue;
	TRIGGERVALUE : ITypedValue;
	LATCHVAR1VALUE : ITypedValue;
	LATCHVAR2VALUE : ITypedValue;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION