FUNCTION SCANUNSIGNEDINT : BOOL
VAR_INPUT
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	IOFFSET : INT;
	ILENGTHPREFIX : INT;
END_VAR
VAR_OUTPUT
	USIVALUE : USINT;
	ITOTALPLACEHOLDERLENGTH : INT;
END_VAR
END_FUNCTION