FUNCTION SYSTIMERTCCONVERTHIGHRESLOCALTODATE2 : UDINT
VAR_INPUT
	IOFFSET : INT;
END_VAR
VAR_OUTPUT
	IOFFSETACTUAL : INT;
END_VAR
VAR_IN_OUT
	PTIMESTAMP : Timestamp;
	PDATE : SYSTIMEDATE;
END_VAR
END_FUNCTION