FUNCTION L_UMTP_DROT2DABC : BOOL
VAR_INPUT
	PARAM : REFERENCE TO L_UMTP_RotParam;
	DROT : REFERENCE TO L_UMTP_Matrix3x3;
END_VAR
VAR_OUTPUT
	DPHIA : LREAL;
	DPHIB : LREAL;
	DPHIC : LREAL;
END_VAR
END_FUNCTION