FUNCTION L_UMTP_2DINTERPOLATIONLINEAR : BOOL
VAR_INPUT
	ALRX : POINTER TO LREAL;
	ALRY : POINTER TO LREAL;
	ALRZ : POINTER TO LREAL;
	LRX : LREAL;
	LRY : LREAL;
END_VAR
VAR_OUTPUT
	XERROR : BOOL;
	EERRORID : L_IE1P_Error;
	LRZ : LREAL;
END_VAR
END_FUNCTION