FUNCTION L_UMTP_BILINEARINTERPOLATION : BOOL
VAR_INPUT
	LRX0 : LREAL;
	LRX1 : LREAL;
	LRY0 : LREAL;
	LRY1 : LREAL;
	LRZ00 : LREAL;
	LRZ01 : LREAL;
	LRZ10 : LREAL;
	LRZ11 : LREAL;
	LRX : LREAL;
	LRY : LREAL;
END_VAR
VAR_OUTPUT
	LRZ : LREAL;
END_VAR
END_FUNCTION