FUNCTION VISUDLGUTIL_CLOSENUMPADEXTENDED2 : BOOL
VAR_INPUT
	FLAGS : DWORD;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	STMIN : STRING;
	STMAX : STRING;
	IFORMATVALUE : INT;
	BINITFORMATVALUE : BOOL;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION