FUNCTION VISUDLG_PROCESSBACKW
VAR_IN_OUT
	WSTOUTPUTVALUE : WSTRING;
	WSTVARIABLEVALUE : WSTRING;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
	BINIT : BOOL;
END_VAR
END_FUNCTION