// The LSP's OWN slug→(CODESYS code, docs URL) map — the authoritative RUNTIME source, engineered here in the
// LSP, NOT derived from any test file. Emitting a diagnostic stamps the recognizable `Cnnnn` + docs link from
// this table. `docs/codesys-reference/error-catalog.json` is a separate TEST fixture; a consistency test
// (error-catalog.test.ts) asserts the two agree, so a newly-mapped code can't be added to one and forgotten
// in the other. When adding a check that mirrors a CODESYS code, add its row here.

/** slug (our diagnostic `code`) → [CODESYS `Cnnnn`, docs URL]. When a slug covers several codes, its primary one. */
export const CODESYS_CODE_MAP: Readonly<Record<string, readonly [code: string, url: string]>> = {
  "constant-too-large": ["C0001", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0001.html"],
  "syntax-error": ["C0002", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0002.html"],
  "invalid-bit-number": ["C0003", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0003.html"],
  "unknown-member": ["C0004", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0004.html"],
  "empty-block": ["C0013", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0013.html"],
  "not-assignment-target": ["C0018", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0018.html"],
  "operator-operand-count": ["C0022", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0022.html"],
  "at-address": ["C0030", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0030.html"],
  "assignment-type-mismatch": ["C0032", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0032.html"],
  "pointer-not-convertible": ["C0033", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0033.html"],
  "invalid-call-target": ["C0035", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0035.html"],
  "unknown-named-argument": ["C0037", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0037.html"],
  "unknown-named-output": ["C0038", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0038.html"],
  "in-out-not-assigned": ["C0039", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0039.html"],
  "function-argument-count": ["C0040", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0040.html"],
  "in-out-needs-writable": ["C0041", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0041.html"],
  "input-assignment-missing": ["C0044", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0044.html"],
  "this-not-allowed": ["C0045", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0045.html"],
  "unresolved-identifier": ["C0046", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0046.html"],
  "indexing-non-array": ["C0047", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0047.html"],
  "array-index-count": ["C0048", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0048.html"],
  "array-index-out-of-bounds": ["C0049", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0049.html"],
  "attribute-value-string": ["C0051", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0051.html"],
  "bit-access-on-call": ["C0061", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0061.html"],
  "deref-non-pointer": ["C0064", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0064.html"],
  "incompatible-comparison": ["C0066", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0066.html"],
  "compare-array": ["C0068", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0068.html"],
  "compare-array-mismatch": ["C0069", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0069.html"],
  "ini-needs-instance": ["C0070", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0070.html"],
  "operator-not-possible": ["C0072", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0072.html"],
  "unexpected-array-init": ["C0074", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0074.html"],
  "array-init-count": ["C0075", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0075.html"],
  "unexpected-struct-init": ["C0076", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0076.html"],
  "fb-not-instantiated": ["C0080", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0080.html"],
  "orphan-conditional-pragma": ["C0081", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0081.html"],
  "interface-not-found": ["C0086", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0086.html"],
  "missing-interface-implementation": ["C0087", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0087.html"],
  "override-mismatch-interface": ["C0089", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0089.html"],
  "base-class-not-found": ["C0090", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0090.html"],
  "circular-inheritance": ["C0091", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0091.html"],
  "override-mismatch-base": ["C0094", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0094.html"],
  "multiple-inheritance": ["C0096", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0096.html"],
  "duplicate-inherited-variable": ["C0097", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0097.html"],
  "deprecated-functionblock": ["C0098", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0098.html"],
  "data-recursion": ["C0101", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0101.html"],
  "jump-invalid-destination": ["C0114", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0114.html"],
  "jump-label-duplicate": ["C0116", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0116.html"],
  "jump-label-undefined": ["C0117", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0117.html"],
  "jump-label-unreferenced": ["C0118", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0118.html"],
  "fb-lifecycle-signature": ["C0119", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0119.html"],
  "super-not-allowed": ["C0122", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0122.html"],
  "enum-init-not-convertible": ["C0124", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0124.html"],
  "pointer-index-arity": ["C0126", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0126.html"],
  "method-referenced-without-parens": ["C0130", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0130.html"],
  "invalid-adr-operand": ["C0131", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0131.html"],
  "exit-outside-loop": ["C0132", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0132.html"],
  "ambiguous-global": ["C0136", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0136.html"],
  "no-op-statement": ["C0139", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0139.html"],
  "reference-assign-target": ["C0140", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0140.html"],
  "reference-assign-write": ["C0141", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0141.html"],
  "duplicate-declaration": ["C0142", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0142.html"],
  "property-lacks-getter": ["C0143", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0143.html"],
  "inheritance-not-allowed": ["C0144", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0144.html"],
  "function-implements": ["C0145", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0145.html"],
  "var-in-interface": ["C0149", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0149.html"],
  "array-bound-non-const": ["C0161", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0161.html"],
  "array-init-count-non-const": ["C0162", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0162.html"],
  "misplaced-var-config": ["C0168", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0168.html"],
  "var-section-placement": ["C0169", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0169.html"],
  "retain-not-allowed": ["C0175", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0175.html"],
  "not-instantiable": ["C0177", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0177.html"],
  "inout-no-external-access": ["C0178", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0178.html"],
  "fb-init-inout": ["C0179", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0179.html"],
  "return-type-not-allowed": ["C0182", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0182.html"],
  "call-result-access": ["C0185", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0185.html"],
  "sign-change-conversion": ["C0195", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0195.html"],
  "narrowing-conversion": ["C0197", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0197.html"],
  "string-constant-too-long": ["C0198", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0198.html"],
  "interface-not-instantiated": ["C0199", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0199.html"],
  "in-out-type-mismatch": ["C0201", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0201.html"],
  "bit-wrong-container": ["C0203", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0203.html"],
  "bit-wrong-block": ["C0204", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0204.html"],
  "pointer-to-bit": ["C0205", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0205.html"],
  "bit-array-base": ["C0206", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0206.html"],
  "binary-op-type-mismatch": ["C0208", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0208.html"],
  "case-label-duplicate": ["C0216", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0216.html"],
  "case-label-in-range": ["C0217", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0217.html"],
  "case-label-non-const": ["C0218", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0218.html"],
  "case-overlapping-ranges": ["C0219", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0219.html"],
  "output-reference-type": ["C0222", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0222.html"],
  "call-recursion": ["C0224", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0224.html"],
  "const-init-non-const": ["C0227", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0227.html"],
  "constant-no-initial-value": ["C0228", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0228.html"],
  "type-name-as-value": ["C0230", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0230.html"],
  "array-init-nesting": ["C0232", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0232.html"],
  "array-init-element": ["C0233", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0233.html"],
  "query-interface-operand": ["C0234", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0234.html"],
  "external-no-global": ["C0237", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0237.html"],
  "external-initializer": ["C0238", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0238.html"],
  "query-pointer-operand": ["C0240", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0240.html"],
  "delete-non-pointer": ["C0242", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0242.html"],
  "loop-exit-constant": ["C0266", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0266.html"],
  "unknown-attribute": ["C0351", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0351.html"],
  "enum-comparison": ["C0354", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0354.html"],
  "adr-on-bit": ["C0355", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0355.html"],
  "obsolete-usage": ["C0357", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0357.html"],
  "inout-own-access": ["C0371", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0371.html"],
  "message-pragma-warning": ["C0373", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0373.html"],
  "interface-implements": ["C0421", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0421.html"],
  "inout-in-initializer": ["C0441", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0441.html"],
  "new-in-expression": ["C0454", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0008-2040066.html"],
  "multiple-assignment-new": ["C0509", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0509.html"],
  "abstract-assign": ["C0511", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0511.html"],
  "input-default-composite": ["C0525", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0525.html"],
  "default-not-constant": ["C0526", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0526.html"],
  "abstract-output-default": ["C0533", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0533.html"],
  "union-inheritance": ["C0542", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0542.html"],
  "reserved-keyword": ["C0543", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0543.html"],
  "pack-mode-not-allowed": ["C0550", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0550.html"],
  "fb-reinit-shape": ["C0566", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0566.html"],
  "duplicate-method": ["C0582", "https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_error_c0582.html"],
}

/** The CODESYS `Cnnnn` + docs URL a diagnostic slug mirrors, or undefined for an unmapped slug. */
export function codesysCodeFor(ourCode: string): { code: string; url: string } | undefined {
  const m = CODESYS_CODE_MAP[ourCode]
  return m ? { code: m[0], url: m[1] } : undefined
}
