FUNCTION STKOPEN : CS.PROC_STATE
VAR_INPUT
	ECMD : CS.PROC_CMD;
	USINETID : USINT;
	USINODEID : USINT;
	UIBAUDRATE : UINT;
	ESPEC : CS.STK_SPEC;
END_VAR
VAR_OUTPUT
	EERROR : CS.ERROR;
END_VAR
END_FUNCTION