FUNCTION L_TB2P_TRANSITIONSYNCINALLOWEDDIRECTION : BOOL
VAR_INPUT
	XACTMASTERDIRVALID : BOOL;
	IACTMASTERDIRECTION : INT := 0;
	LRCYCLELENGTH : LREAL;
	LRMASTERPOSFORSYNC : LREAL;
	LRSETSLAVEPOS : LREAL;
	LRMASTERVELFORSYNC : LREAL;
	LRSETSLAVEVELOCITY : LREAL;
	DWLIMITERCONTROL : DWORD;
	EALLOWEDDIRECTION : L_TB2P_AllowedDirection;
	ESYNCMODE : L_TB2P_SyncMode;
	LRSYNCVEL : LREAL;
	LRSLAVESYNCINDIST : LREAL;
END_VAR
VAR_OUTPUT
	XDIRECTIONDISABLED : BOOL;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION