FUNCTION L_TB2P_HLPDELTAVELTIMETOCONTANTVEL : BOOL
VAR_INPUT
	LRACCSTART : LREAL;
	LRMAXJERK : LREAL;
	WMODE : WORD;
END_VAR
VAR_OUTPUT
	LRVEL : LREAL;
	LRTIME : LREAL;
	LRDIST : LREAL;
END_VAR
END_FUNCTION