FUNCTION L_TB2P_HLPCALCTARGETANDKOEFPOLY5THORD : ARRAY [0..5] OF LREAL
VAR_INPUT
	LRYVELSTART : LREAL;
	LRYVELEND : LREAL;
END_VAR
VAR_OUTPUT
	ALRKOEF : ARRAY [0..5] OF LREAL;
	LRYPOSEND : LREAL;
END_VAR
END_FUNCTION