FUNCTION L_TF2P_GETSTARTMOVETOTARGETPOS : BOOL
VAR_INPUT
	MASTERVALUES : L_MC1P_IAXIS_REF_MASTERVALUES;
	LRSYNCDEC : LREAL;
	LRSYNCJERK : LREAL;
	LRTARGETPOS : LREAL;
END_VAR
VAR_IN_OUT
	AXIS : AXIS_REF;
END_VAR
END_FUNCTION