FUNCTION VISHCLIENTCREATE : INT
VAR_INPUT
	STAPPNAME : STRING;
	CLIENTTYPE : UINT;
	DWEXTERNID : DWORD;
	DWCREATIONFLAGS : DWORD;
	NUMTAGS : INT;
	PTAGS : POINTER TO Visu_ClientTagData;
END_VAR
VAR_OUTPUT
	DWEXTERNIDCREATED : DWORD;
END_VAR
END_FUNCTION