FUNCTION REPLACEALARMPLACEHOLDERSCONVERTED : BOOL
VAR_INPUT
	CBSMESSAGE : REFERENCE TO CharBufferString;
	CBSRESULT : REFERENCE TO CharBufferString;
	ITFALARMMETAOBJECTSTUB3 : IAlarmMetaObjectStub3;
	CBPMESSAGE : CharBufferPtr;
	STALARMID : STRING;
	USIPRIORITY : USINT;
	STALARMCLASSNAME : STRING;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION