FUNCTION REPLACEALARMPLACEHOLDERS4IALARM : BOOL
VAR_INPUT
	IWHICHMESSAGE : INT;
	RCBSMESSAGE : REFERENCE TO CharBufferString;
	RCBSRESULT : REFERENCE TO CharBufferString;
	ITFALARM4 : IAlarm4;
	CBPMESSAGE : CharBufferPtr;
	ESTATE : AlarmState;
	SEXPRESSION : STRING(255);
	USIPRIORITY : USINT;
	SALARMCLASSNAME : STRING;
	SALARMID : STRING;
	SDATEFORMATPATTERN : STRING := '';
	STIMEFORMATPATTERN : STRING := '';
END_VAR
END_FUNCTION