FUNCTION SETTGGETINTVALUE : RTS_IEC_RESULT
VAR_INPUT
	PSZCOMPONENT : REFERENCE TO STRING;
	PSZKEY : REFERENCE TO STRING;
	PIVALUE : POINTER TO DINT;
	IDEFAULT : DINT;
	BCACHED : DINT;
END_VAR
END_FUNCTION