FUNCTION _FLATCREATEP : CAA.HANDLE
VAR_INPUT
	IDMINKEY : CAA.IDENT;
	IDMAXKEY : CAA.IDENT;
	CTNUMKEY : CAA.COUNT;
	SZMEMSIZE : CAA.SIZE;
	PMEMORY : CAA.PVOID;
	EENABLE : CB.EVENT;
	EDISABLE : CB.EVENT;
	EUPDATE : CB.EVENT;
	EREAD : CB.EVENT;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION