FUNCTION _XCHGCREATEH : CAA.HANDLE
VAR_INPUT
	CTNUMMSG : CAA.COUNT;
	SZBLOCKSIZE : CAA.SIZE;
	CTNUMPRIOS : CAA.COUNT;
	ESENDMSG : CB.EVENT;
	ERECEIVEMSG : CB.EVENT;
	EXCHGEMPTY : CB.EVENT;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION