/**
 * THE FRONT-END — `syntax → symbols → types`, with `library` beside them (openspec frontend-conformance design.md P2),
 * re-exported by name for the package barrel (`src/index.ts`) alone. Every other consumer imports a sub-layer's own
 * index (`frontend/<layer>/index.js`), and `library` only through `frontend/library/index.js`.
 */
export {
  allUnits,
  BINARY_PRECEDENCE,
  bodyReader,
  calendarNanoseconds,
  CODESYS_ONLY_KEYWORDS,
  TWINCAT_LITERAL_PREFIXES,
  declarationAttributes,
  decodeStringLiteral,
  dimText,
  DURATION_UNITS_NS,
  exprChildren,
  exprText,
  graphicalBodies,
  graphicalMarkerLanguage,
  IMPLEMENTATION_KEYWORD,
  implementationLine,
  implementationWords,
  isGraphicalBody,
  isNeverShown,
  isRetiredComment,
  isSelfRef,
  isStBody,
  isTrivia,
  lex,
  memberAttributes,
  parseDocument,
  parseExprFromTokens,
  parseSource,
  bodyStatements,
  sourceStatements,
  parseTypeExprFromTokens,
  renderTypeExpr,
  sameName,
  selfRefKind,
  sourceObjectOf,
  spanContains,
  statedLine,
  stmtChildLists,
  stmtExprs,
  unitAttributes,
  unitBodies,
  varInputParams,
  walkAllExprs,
  walkExpr,
  walkStatements,
  zeroSpan,
  type Action,
  type AggregateElement,
  type AggregateInit,
  type ArrayDim,
  type Assignment,
  type BinaryExpr,
  type BodySpan,
  type CallArg,
  type CallExpr,
  type CaseArm,
  type CaseStatement,
  type Dialect,
  type EnumBody,
  type EnumValue,
  type Expr,
  type Function,
  type FunctionBlock,
  type GlobalVarList,
  type IdentExpr,
  type Identifier,
  type Initializer,
  type Interface,
  type InterfaceMethod,
  type InterfaceProperty,
  type Literal,
  type MemberExpr,
  type Method,
  type Namespace,
  type ParseError,
  type ParseOptions,
  type ParseResult,
  type Program,
  type Property,
  type PropertyAccessor,
  type Span,
  type Statement,
  type StatementList,
  type StructBody,
  type Token,
  type TokenKind,
  type TopLevel,
  type TypeDecl,
  type TypeExpr,
  type UnionBody,
  type VarDecl,
  type VarSection,
  type VarSectionKind,
} from "./syntax/index.js"
export {
  baseOf,
  bodies,
  bodiesAt,
  build,
  childScopesByName,
  defineSymbol,
  dialectOf,
  enclosingPou,
  extendsChain,
  findChildScope,
  findScopeByName,
  forEachDecl,
  forEachExpr,
  gvlName,
  hasUnresolvedBase,
  isLibrarySymbol,
  isPouSymbol,
  libraryRank,
  lookup,
  lookupLocal,
  lookupMember,
  manifestsByTitle,
  memoByProject,
  pickForAsker,
  POU_SYMBOL_KINDS,
  bareEnumMember,
  resolveBareEnumMember,
  resolveGvlMember,
  resolveQualifiedConst,
  rootOf,
  scopeForUnit,
  scopeUri,
  symbolDefinedAt,
  visibleNames,
  type BareEnumMember,
  type LookupResult,
  type Scope,
  type ScopeKind,
  type Symbol,
  type SymbolKind,
  type SymbolTableInput,
  type UnitBody,
} from "./symbols/index.js"
export {
  ANY_FAMILIES,
  ARITHMETIC_OPERATORS,
  BIT_OPERATOR_FUNCTIONS,
  BUILTIN_RESULT,
  canonicalElem,
  checkedMeetType,
  checkedNegationType,
  classifyConversion,
  CODESYS_ONLY_TYPES,
  commonType,
  COMPARISON_FUNCTIONS,
  comparisonConverts,
  constancyOf,
  constantSlotType,
  constEval,
  DEFAULT_STRING_LENGTH,
  ELEMENTARY_TYPES,
  elementaryRef,
  elementaryType,
  elementaryTypeRef,
  elemOf,
  enumDefault,
  exptResultType,
  inferExprType,
  inlineEnumDefault,
  integerLiteralType,
  integerOfWidth,
  inTypeGroup,
  isAssignable,
  isDialectType,
  isDuration,
  isEnumValueRef,
  isIntegerType,
  isIntLiteral,
  isKnownPrimitive,
  isNumericType,
  pointerFits,
  isSameType,
  isTemporal,
  literalCapacityType,
  literalCheckType,
  literalErrorType,
  literalOwnType,
  literalType,
  memberScopeOf,
  narrowDateWideDuration,
  operandConversion,
  operandFamilyRule,
  parseConversionName,
  PLATFORM_ALIASES,
  promoteForRuntime,
  REAL_LITERAL_TYPE,
  REAL_MAX_MAGNITUDE,
  renderType,
  resolveCallee,
  resolveMemberChain,
  resolveNamedType,
  resolveTypeExpr,
  temporalResultType,
  unaryOperandConversion,
  UNKNOWN,
  type ArrayTypeInfo,
  type CalleeInfo,
  type ConstValue,
  type ConversionKind,
  type ElementaryType,
  type ElementaryTypeRef,
  type FunctionBlockType,
  type Type,
} from "./types/index.js"
