FUNCTION L_MC1P_FINDPDODATAINCONNECTOR : POINTER TO BYTE
VAR_INPUT
	PCONNECTOR : POINTER TO IoConfigConnector;
	UIINDEX : WORD;
	USISUBINDEX : USINT;
	XWRITEACCESS : BOOL;
END_VAR
VAR_OUTPUT
	USISIZE : USINT;
END_VAR
END_FUNCTION