FUNCTION MEMCOPY_INTERNAL : POINTER TO BYTE
VAR_INPUT
	PDEST : POINTER TO BYTE;
	PSRC : POINTER TO BYTE;
	DWSIZE : DWORD;
END_VAR
MEMCOPY_INTERNAL := PDEST;
WHILE DWSIZE > 0 DO
	PDEST^ := PSRC^;
	PDEST := PDEST + 1;
	PSRC := PSRC + 1;
	DWSIZE := DWSIZE - 1;
END_WHILE
END_FUNCTION