FUNCTION GETTIMESTAMPSDIFFERENCE : ERROR
VAR_INPUT
	ULIDATETIMEFIRST : ULINT;
	ULIDATETIMESECOND : ULINT;
END_VAR
VAR_OUTPUT
	ULIDAYS : ULINT;
	UIHOURS : HOUR;
	UIMINUTES : MINUTE;
	UISECONDS : SECOND;
	UIMILLISECONDS : MILLISECOND;
END_VAR
END_FUNCTION