FUNCTION L_MC2P_CAMGETXVALUE2 : BOOL
VAR_INPUT
	ITFCAMDATA : L_MC2P_IMotionData;
	IDX1 : UDINT;
	IDX2 : UDINT;
	ECAMTYPE : L_MC2P_CamType;
	LRMASTEP : LREAL;
	LRXSTART : LREAL;
END_VAR
VAR_OUTPUT
	LRX1 : LREAL;
	LRX2 : LREAL;
END_VAR
END_FUNCTION