FUNCTION PRINTF : BOOL
VAR_INPUT
	CBSRESULT : REFERENCE TO CharBufferString;
	CBSFORMAT : REFERENCE TO CharBufferString;
	PVALUE : POINTER TO BYTE;
	TYPECLASS : __SYSTEM.TYPE_CLASS;
END_VAR
END_FUNCTION