FUNCTION STRREPLACEW : BOOL
VAR_INPUT
	PSTINPUT : POINTER TO WSTRING(255);
	UIINPUTBUFFERSIZE : UINT;
	PSTREPLACEWITH : POINTER TO WSTRING(255);
	ILENGTHINPUT : INT;
	ILENGTHTOREPLACE : INT;
	ILENGTHTOREPLACEWITH : INT;
	IPOSITION : INT;
END_VAR
END_FUNCTION