FUNCTION FINDBYBROWSENAME : POINTER TO SymbolsBaseNode
VAR_INPUT
	LIST : POINTER TO POINTER TO SymbolsBaseNode;
	NUMELEMENTS : DINT;
	PBROWSENAME : POINTER TO OpcUa_QualifiedName;
END_VAR
VAR_OUTPUT
	INDEX : DINT;
END_VAR
END_FUNCTION