FUNCTION L_IE1P_GETHIGHESTREACTION : BOOL
VAR_INPUT
	EREACTION1 : L_IE1P_Reaction;
	MODULEHANDLER1 : POINTER TO BYTE;
	EREACTION2 : L_IE1P_Reaction;
	MODULEHANDLER2 : POINTER TO BYTE;
END_VAR
VAR_OUTPUT
	EREACTION : L_IE1P_Reaction;
	MODULEHANDLER : POINTER TO BYTE;
END_VAR
END_FUNCTION