FUNCTION JOINDATETIME : ULINT
VAR_INPUT
	UIYEAR : YEAR;
	UIMONTH : MONTH;
	UIDAY : DAY;
	UIHOUR : HOUR;
	UIMINUTE : MINUTE;
	UISECOND : SECOND;
	UIMILLISECONDS : MILLISECOND;
END_VAR
VAR_OUTPUT
	EERRORID : ERROR := ERROR.NO_ERROR;
END_VAR
END_FUNCTION