FUNCTION UTILGETMD5HASH : BOOL
VAR_INPUT
	PDATA : POINTER TO BYTE;
	DWSIZE : DWORD;
	PMD5HASH : POINTER TO ARRAY [0..15] OF BYTE;
	BADDMAGICNUMBER : BOOL;
	BBYTEORDERMOTOROLAONPOWERPC : BOOL;
END_VAR
END_FUNCTION