FUNCTION SYSDIROPEN : RTS_IEC_HANDLE
VAR_INPUT
	SZDIR : REFERENCE TO STRING;
	SZDIRENTRY : REFERENCE TO STRING;
	DIMAXDIRENTRY : DINT;
	PDIRINFO : POINTER TO DirInfo;
	PRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION