FUNCTION L_MC2P_CAMGETDATA2 : BOOL
VAR_INPUT
	ITFCAMDATA : L_MC2P_IMotionData;
	IDX1 : UDINT;
	IDX2 : UDINT;
	ECAMTYPE : L_MC2P_CamType;
END_VAR
VAR_OUTPUT
	PSCDATA1 : POINTER TO BYTE;
	PSCDATA2 : POINTER TO BYTE;
END_VAR
END_FUNCTION