FUNCTION L_MC2P_CAMGETYVALUE2 : BOOL
VAR_INPUT
	ITFCAMDATA : L_MC2P_IMotionData;
	IDX1 : UDINT;
	IDX2 : UDINT;
	ECAMTYPE : L_MC2P_CamType;
END_VAR
VAR_OUTPUT
	LRY1 : LREAL;
	LRY2 : LREAL;
END_VAR
END_FUNCTION