FUNCTION DTSPLIT : ERROR
VAR_INPUT
	DTDATEANDTIME : DATE_AND_TIME;
	PUIYEAR : POINTER TO UINT;
	PUIMONTH : POINTER TO UINT;
	PUIDAY : POINTER TO UINT;
	PUIHOUR : POINTER TO UINT;
	PUIMINUTE : POINTER TO UINT;
	PUISECOND : POINTER TO UINT;
END_VAR
END_FUNCTION