FUNCTION TODSPLIT : ERROR
VAR_INPUT
	TODTIME : TIME_OF_DAY;
	PUIHOUR : POINTER TO UINT;
	PUIMINUTE : POINTER TO UINT;
	PUISECOND : POINTER TO UINT;
	PUIMILLISECOND : POINTER TO UINT;
END_VAR
END_FUNCTION