FUNCTION L_IHMP_SIMPLEREGISTERCOMPONENTFORLEM : BOOL
VAR_INPUT
	SCOMPNAME : STRING;
	SPATH : STRING(255);
	UILAYER : UINT;
	UDICOMPTYPE : UDINT;
	UITEXTREFID : UINT;
	UIREAKTIONITF : UINT;
END_VAR
VAR_OUTPUT
	REGISTERDLEMHANDLE : RTS_IEC_HANDLE;
	REGISTERDLMHHANDLE : RTS_IEC_HANDLE;
END_VAR
END_FUNCTION