FUNCTION L_IMHP_LM_CHECKLICENSESTRING : BOOL
VAR_INPUT
	SLICINFO : STRING;
END_VAR
VAR_IN_OUT
	UDIAPPLICATIONCREDIT : DWORD;
	ELICENSECLASS : L_IMHP_LM_LicensClass;
	UDILICENSECLASSNUMBER : DWORD;
END_VAR
END_FUNCTION