FUNCTION L_IPAP_CHECKREADRESULT : L_IPAP_REQUEST_STATE
VAR_INPUT
	HREADREQUEST : RTS_IEC_HANDLE;
	PREADBUFFER : POINTER TO BYTE;
	UIBUFFERSIZE : UDINT;
	PREADDATASIZE : POINTER TO UDINT;
	PREADDATATYPE : POINTER TO L_IPAP_DATATYPE;
	PREQUESTRESULT : POINTER TO RTS_IEC_RESULT;
END_VAR
END_FUNCTION