/**
 * Unit tests for pragma hover — hovering on `{attribute 'name'}` should
 * return documentation from the pragma reference catalog, not null.
 */
import { describe, expect, it } from "bun:test";
import { hover } from "../../lsp/queries/hover.js";
import { Workspace } from "../../lsp/workspace.js";

function setup(source: string) {
	const ws = new Workspace();
	ws.openDocument("file:///t.st", source, 0);
	const doc = ws.getDocument("file:///t.st")!;
	const project = ws.getProjectScope();
	return { doc, project };
}

function positionOf(source: string, searchText: string, offsetInMatch = 2) {
	const idx = source.indexOf(searchText);
	if (idx < 0) throw new Error(`"${searchText}" not found in source`);
	const target = idx + offsetInMatch;
	const before = source.slice(0, target);
	const lines = before.split("\n");
	return {
		line: lines.length - 1,
		character: (lines[lines.length - 1] ?? "").length,
	};
}

describe("hover: pragma tooltip", () => {
	it("returns docs when hovering inside {attribute 'qualified_only'}", () => {
		const src = `{attribute 'qualified_only'}
VAR_GLOBAL
  x : INT;
END_VAR
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "qualified_only", 4);
		const result = hover({ doc, position, project, showSource: false });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("qualified_only");
	});

	it("returns docs when hovering inside {attribute 'no_init'}", () => {
		const src = `FUNCTION_BLOCK FB_X
VAR
  {attribute 'no_init'}
  x : INT;
END_VAR
END_FUNCTION_BLOCK
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "no_init", 2);
		const result = hover({ doc, position, project, showSource: false });
		expect(result).not.toBeNull();
		// Catalog entry is "noinit" (with aliases for no_init / no-init).
		expect(result?.contents.value).toContain("noinit");
	});

	it("returns null when hovering outside any pragma or identifier", () => {
		const src = `FUNCTION_BLOCK FB_X
END_FUNCTION_BLOCK
`;
		const { doc, project } = setup(src);
		// Position on the blank line
		const result = hover({ doc, position: { line: 1, character: 0 }, project });
		expect(result).toBeNull();
	});
});

describe("hover: graphical marker tooltip", () => {
	it("returns a tooltip when hovering on (* @volt-graphical: FBD *)", () => {
		const src = `FUNCTION_BLOCK FB_X
END_FUNCTION_BLOCK

(* @volt-graphical: FBD *)
ACTION Cyclic
x := 1;
END_ACTION
`;
		const { doc, project } = setup(src);
		// Cursor inside the marker comment on the 4th line
		const position = positionOf(src, "@volt-graphical", 4);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("FBD");
		expect(result?.contents.value).toContain("generated by Volt");
	});

	it("returns a tooltip for SFC marker", () => {
		const src = `FUNCTION_BLOCK FB_X
END_FUNCTION_BLOCK

(* @volt-graphical: SFC *)
ACTION Step1
END_ACTION
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "@volt-graphical", 4);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("SFC");
	});

	it("returns null when hovering on a regular comment that is not a graphical marker", () => {
		const src = `FUNCTION_BLOCK FB_X
(* just a normal comment *)
END_FUNCTION_BLOCK
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "just a normal", 2);
		const result = hover({ doc, position, project });
		expect(result).toBeNull();
	});
});

describe("hover: folder annotation tooltip", () => {
	it("returns a tooltip when hovering on (* folder: Control *) on a method signature", () => {
		const src = `FUNCTION_BLOCK FB_Motor
VAR
  speed: REAL;
END_VAR
END_FUNCTION_BLOCK

METHOD Start : BOOL    (* folder: Control *)
VAR_INPUT
END_VAR
END_METHOD
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "folder: Control", 4);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("Control");
		expect(result?.contents.value).toContain("folder");
		expect(result?.contents.value).toContain("project tree");
	});

	it("returns a tooltip for a multi-level nested path", () => {
		const src = `FUNCTION_BLOCK FB_Motor
END_FUNCTION_BLOCK

METHOD Deep : BOOL    (* folder: Control/Option1 *)
END_METHOD
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "folder: Control/Option1", 8);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("Control/Option1");
		expect(result?.contents.value).toContain("nested");
		expect(result?.contents.value).toContain("Control");
		expect(result?.contents.value).toContain("Option1");
	});

	it("returns a tooltip for a three-level deep path", () => {
		const src = `FUNCTION_BLOCK FB_Motor
END_FUNCTION_BLOCK

ACTION Reset    (* folder: A/B/C *)
END_ACTION
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "folder: A/B/C", 4);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("A/B/C");
	});

	it("cursor at start of (* folder: ... *) still returns tooltip", () => {
		const src = `FUNCTION_BLOCK FB_Motor
END_FUNCTION_BLOCK

METHOD Init : BOOL    (* folder: Setup *)
END_METHOD
`;
		const { doc, project } = setup(src);
		// Position right on '(' of '(*'
		const position = positionOf(src, "(* folder: Setup", 0);
		const result = hover({ doc, position, project });
		expect(result).not.toBeNull();
		expect(result?.contents.value).toContain("Setup");
	});

	it("returns null when hovering on a regular comment (no folder: prefix)", () => {
		const src = `FUNCTION_BLOCK FB_X
END_FUNCTION_BLOCK

METHOD Init : BOOL    (* some unrelated comment *)
END_METHOD
`;
		const { doc, project } = setup(src);
		const position = positionOf(src, "unrelated comment", 4);
		const result = hover({ doc, position, project });
		expect(result).toBeNull();
	});

	it("hovering outside the (* folder: *) comment on the same line returns null", () => {
		// The folder annotation is at the end of the signature line.
		// Hovering on the METHOD keyword itself (before the comment) should
		// NOT trigger the folder tooltip.
		const src = `FUNCTION_BLOCK FB_Motor
END_FUNCTION_BLOCK

METHOD Start : BOOL    (* folder: Control *)
END_METHOD
`;
		const { doc, project } = setup(src);
		// Position on 'M' in 'METHOD' — well before the comment
		const position = positionOf(src, "METHOD Start", 0);
		const result = hover({ doc, position, project });
		// METHOD keyword is not inside the folder comment — no folder tooltip.
		expect(result?.contents.value ?? "").not.toContain("project tree");
	});
});
