FUNCTION _FLATCREATEH : CAA.HANDLE
VAR_INPUT
	IDMINKEY : CAA.IDENT;
	IDMAXKEY : CAA.IDENT;
	CTNUMKEYS : CAA.COUNT;
	EENABLE : CB.EVENT;
	EDISABLE : CB.EVENT;
	EUPDATE : CB.EVENT;
	EREAD : CB.EVENT;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION