FUNCTION XCHGCREATEP : CAA.HANDLE
VAR_INPUT
	SZBLOCKSIZE : CAA.SIZE;
	CTNUMPRIOS : CAA.COUNT;
	SZMEMSIZE : CAA.SIZE;
	PMEMORY : CAA.PVOID;
	ESENDMSG : CB.EVENT;
	ERECEIVEMSG : CB.EVENT;
	EXCHGEMPTY : CB.EVENT;
	PEERROR : POINTER TO ERROR;
END_VAR
END_FUNCTION