FUNCTION VISUDLG_PROCESSBACKPREPARE : BOOL
VAR_INPUT
	XPASSWORD : BOOL;
END_VAR
VAR_IN_OUT
	STOUTPUTVALUE : STRING;
	STVARIABLEVALUE : STRING;
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
	BINIT : BOOL;
END_VAR
END_FUNCTION