FUNCTION VISUDLGUTIL_ADJUSTCARETANDSELECTIONAFTERNUMBERFORMATCHANGE : BOOL
VAR_INPUT
	ITEXTLENGTHBEFORECHANGE : INT;
	STVARIABLEVALUE : STRING;
END_VAR
VAR_IN_OUT
	ICARETPOSITION : INT;
	ISELECTIONSTART : INT;
	ISELECTIONEND : INT;
END_VAR
END_FUNCTION