/**
 * Fork divergence guard.
 *
 * Enforces the Volt fork invariant: **we never modify or delete opencode
 * upstream source — Volt is purely additive** (product in `packages/volt-*`,
 * plus new files at opencode's extension points). The only upstream files
 * we are allowed to touch are a small, explicit set of integration seams.
 *
 * This script is the always-accurate answer to "where do the fork's changes
 * live?" — it lists every upstream file the fork modified/deleted and fails
 * if any is outside the allowlist. Run it after every `git merge upstream/dev`.
 *
 *   bun run volt-scripts/check-divergence.ts            # compare against upstream/dev
 *   bun run volt-scripts/check-divergence.ts upstream/main
 *
 * Exit 0 = clean (only allowlisted seams touched); exit 1 = a new divergence
 * appeared (an edit/delete to upstream source) — investigate before merging.
 */
import { execSync } from "node:child_process"

const upstreamRef = process.argv[2] ?? "upstream/dev"

// The ONLY upstream files the fork may modify. Everything else upstream must
// stay byte-identical; all Volt code is additive (new files / volt-* packages).
const ALLOWED_MODIFICATIONS = new Set<string>([
  "bun.lock", // workspace deps for the volt-* packages (regenerated by `bun install`)
  ".opencode/opencode.jsonc", // Volt LSP registration + `volt` CLI permission gates (config seam)
  "turbo.json", // test-task entries for the volt-* packages
  ".husky/pre-push", // scope the pre-push typecheck to volt-* packages
  ".gitignore", // local `/memory` Claude-memory junction ignore
])

// Paths that are wholly fork-owned — changes here never count as divergence.
const FORK_OWNED_PREFIXES = ["packages/volt-", "volt-scripts/"]

function isForkOwned(path: string): boolean {
  return FORK_OWNED_PREFIXES.some((p) => path.startsWith(p))
}

const out = execSync(`git diff --name-status ${upstreamRef} HEAD`, { encoding: "utf8" })

const violations: string[] = []
const allowed: string[] = []

for (const line of out.split("\n")) {
  if (line.trim() === "") continue
  const [status, ...rest] = line.split("\t")
  const path = rest.join("\t")
  const code = (status ?? "").charAt(0)

  if (isForkOwned(path)) continue // volt-* packages — additive, exempt
  if (code === "A") continue // a NEW fork file (didn't exist upstream) — additive, fine

  // M (modified) or D (deleted) of an upstream-tracked file: only allowlisted seams are OK.
  if (ALLOWED_MODIFICATIONS.has(path)) {
    allowed.push(`${code}  ${path}`)
  } else {
    violations.push(`${code}  ${path}`)
  }
}

console.log(`Fork divergence vs ${upstreamRef}\n`)
console.log(`Allowed integration seams touched (${allowed.length}):`)
for (const a of allowed) console.log(`  ${a}`)

if (violations.length > 0) {
  console.log(`\n✗ UNEXPECTED upstream-source divergence (${violations.length}) — Volt must be additive:`)
  for (const v of violations) console.log(`  ${v}`)
  console.log(`\nEither revert these to upstream, or (if intentional) add them to ALLOWED_MODIFICATIONS in this script.`)
  process.exit(1)
}

console.log(`\n✓ clean — no upstream source modified outside the ${ALLOWED_MODIFICATIONS.size} allowed seams.`)
