/**
 * Export the Volt overlay as a single, version-pinned patch.
 *
 * Volt is an additive overlay on top of opencode (see CLAUDE.md "Fork surface").
 * This bundles the ENTIRE fork delta — the `packages/volt-*` product, the
 * additive integration files, and the handful of config seams — into one patch
 * against a specific opencode commit. Applying it onto a pristine opencode
 * checkout at that commit reconstructs the Volt repo, so opencode itself can
 * stay 100% standard.
 *
 *   bun run volt-scripts/export-overlay.ts                 # vs upstream/dev → dist/volt-overlay/
 *   bun run volt-scripts/export-overlay.ts dist/out upstream/dev
 *
 * Apply to a clean opencode:
 *   git clone <opencode> && cd opencode && git checkout <base-sha>
 *   git apply /path/volt-overlay.patch
 *   bun install
 *
 * It also doubles as an applicability check: if the patch stops applying to a
 * newer opencode release, that release moved something a seam depends on.
 */
import { execSync } from "node:child_process"
import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const outDir = process.argv[2] ?? "dist/volt-overlay"
const upstreamRef = process.argv[3] ?? "upstream/dev"

const git = (cmd: string) => execSync(`git ${cmd}`, { encoding: "utf8", maxBuffer: 256 * 1024 * 1024 })

const baseSha = git(`rev-parse ${upstreamRef}`).trim()
const baseShort = git(`rev-parse --short ${upstreamRef}`).trim()
const headShort = git(`rev-parse --short HEAD`).trim()

// --binary so fork-added binary fixtures (e.g. the CODESYS .project) round-trip.
const patch = git(`diff --binary ${upstreamRef} HEAD`)

// Classify the delta for the summary (additive vs the config seams).
const SEAMS = new Set([".gitignore", ".husky/pre-push", ".opencode/tui.json", "bun.lock"])
const nameStatus = git(`diff --name-status ${upstreamRef} HEAD`).trim().split("\n").filter(Boolean)
let additive = 0
let seam = 0
let other = 0
for (const line of nameStatus) {
  const [status, ...rest] = line.split("\t")
  const path = rest.join("\t")
  if ((status ?? "").charAt(0) === "A") additive++
  else if (SEAMS.has(path)) seam++
  else other++
}

mkdirSync(outDir, { recursive: true })
const patchPath = join(outDir, "volt-overlay.patch")
writeFileSync(patchPath, patch)

const readme = `# Volt overlay — opencode @ ${baseShort}

Generated by \`volt-scripts/export-overlay.ts\`. Reconstructs the Volt fork by applying
one patch onto a pristine opencode checkout, so opencode stays standard.

- Base opencode commit: \`${baseSha}\` (${upstreamRef} at export time)
- Fork tip: \`${headShort}\`
- Files: ${additive} added (product + integration), ${seam} config seams${other > 0 ? `, ${other} other` : ""}

## Apply
\`\`\`bash
git clone https://github.com/anomalyco/opencode.git
cd opencode && git checkout ${baseSha}
git apply /path/to/volt-overlay.patch
bun install
\`\`\`

If \`git apply\` fails on a newer opencode, a seam's surrounding context moved —
re-base the fork (merge upstream) and re-export.
`
writeFileSync(join(outDir, "README.md"), readme)

console.log(`Volt overlay exported → ${outDir}/`)
console.log(`  base opencode: ${baseShort}   fork tip: ${headShort}`)
console.log(`  ${additive} added files, ${seam} config seams${other > 0 ? `, ${other} other` : ""}`)
console.log(`  patch: ${patchPath} (${Math.round(patch.length / 1024)} KB)`)
