FUNCTION L_IMHP_ADDREACTIONCOUNTER : BOOL
VAR_IN_OUT
	REACTIONCOUNTERIN1 : L_IE1P_ReactionCounter;
	REACTIONCOUNTERIN2 : L_IE1P_ReactionCounter;
	REACTIONCOUNTEROUT : L_IE1P_ReactionCounter;
END_VAR
END_FUNCTION