FUNCTION L_IMHP_EM_NOTIFYERRORWITHPAR : UDINT
VAR_INPUT
	ERRORHANDLERID : RTS_IEC_HANDLE;
	WERRORID : WORD;
	WTEXTREFID : WORD;
	SEVERITY : USINT;
	PRIORITY : USINT;
	GROUP : USINT;
	PARCOUNT : UINT;
	PPAR : POINTER TO L_IMHP_EM_ParameterItemShort;
END_VAR
END_FUNCTION