FUNCTION L_IMHP_EM_NOTIFYERRORNOLOGBOOK : UDINT
VAR_INPUT
	ERRORHANDLERID : RTS_IEC_HANDLE;
	WERRORID : WORD;
	WTEXTREFID : WORD;
	SEVERITY : USINT;
	REACTION : UINT;
	PRIORITY : USINT;
	GROUP : USINT;
END_VAR
END_FUNCTION