FUNCTION L_IMHP_ADDSEVERITYCOUNTER : BOOL
VAR_IN_OUT
	SEVERITYCOUNTERIN1 : L_IE1P_SeverityCounter;
	SEVERITYCOUNTERIN2 : L_IE1P_SeverityCounter;
	SEVERITYCOUNTEROUT : L_IE1P_SeverityCounter;
END_VAR
END_FUNCTION