FUNCTION L_TS2P_CALCSYNCTIME : BOOL
VAR_INPUT
	LRACTMATERIALVEL : LREAL;
	LRACCMAX : LREAL;
	LRJERKSTART : LREAL;
	LRJERKEND : LREAL;
END_VAR
VAR_OUTPUT
	LRACCTIME : LREAL;
	LRACCDIST : LREAL;
END_VAR
END_FUNCTION